'use strict';
function renderCurrent(){const t=target(),r=route();$('#routeCounter').textContent=`${state.current+1} / ${r.length}`;$('#currentName').textContent=t.name;$('#currentNote').textContent=t.note;$('#currentTip').textContent=t.tip;$('#currentTag').textContent=`${t.icon} ${categoryNames[t.category]||t.category}`;$('#currentTag').style.background=t.color;$('#hudTarget').textContent=t.short||t.name;$('#hudIcon').textContent=t.icon;$('#hudIcon').style.background=t.color;$('#navigateBtn').href=mapsDir(state.gps?`${state.gps.lat},${state.gps.lon}`:'My Location',`${t.lat},${t.lon}`,'walking');setImage($('#currentPhoto'),$('#currentFallback'),t,true);$('#currentEta').textContent=`planned ${fmtTime(etaFor(state.current))}`;
  const d=state.gps?hav(state.gps,t):NaN;$('#currentDistance').textContent=state.gps?fmtDist(d):'GPS off';$('#hudDistance').textContent=state.gps?`${fmtDist(d)} away · stop ${state.current+1}/${r.length}`:`Stop ${state.current+1}/${r.length} · enable GPS`;
  $('#prevBtn').disabled=state.current===0;$('#skipBtn').disabled=state.current>=r.length-1;$('#arriveBtn').disabled=state.current>=r.length-1 && state.visited.has(t.id);
  const pct=Math.round(state.current/Math.max(1,r.length-1)*100);$('#progressHud').textContent=`${pct}%`;
}
function renderRoute(){const r=route(),box=$('#routeList');box.innerHTML='';r.forEach((s,i)=>{const el=document.createElement('article');el.className=`route-item ${i===state.current?'current':''} ${state.visited.has(s.id)?'done':''}`;const thumb=s.photo?`<img src="${photoUrl(s.photo,240)}" alt="" loading="lazy" onerror="this.remove()">`:s.icon;el.innerHTML=`<div class="route-thumb" style="background:linear-gradient(135deg,${s.color},#ff3ec9)">${thumb}</div><div><h3>${s.name}</h3><p>${fmtTime(etaFor(i))} · ${categoryNames[s.category]||s.category}${state.gps?` · ${fmtDist(hav(state.gps,s))}`:''}</p></div><div class="route-index" style="background:${s.color}">${state.visited.has(s.id)?'✓':i+1}</div>`;el.addEventListener('click',()=>openItem(s,'route',i));box.appendChild(el)});
  const st=routeStats();$('#routeSummary').textContent=`≈${st.km.toFixed(1)} km · ${Math.round(st.stepsLow/1000)}–${Math.round(st.stepsHigh/1000)}k`;
}
function originForDistance(){if(state.gps)return state.gps;if(map){const c=map.getCenter();return{lat:c.lat,lon:c.lng}}return{lat:38.7165,lon:-9.1395};}
function renderNearby(){const o=originForDistance();const all=[...DATA.sidequests.map(s=>({...s,_type:'side'})),...route().filter((_,i)=>i!==state.current).map(s=>({...s,_type:'route'}))].map(s=>({...s,_d:hav(o,s)})).sort((a,b)=>a._d-b._d).slice(0,10);const box=$('#nearbyRow');box.innerHTML='';all.forEach(s=>{const el=document.createElement('article');el.className='poi-card';const media=s.photo?`<img src="${photoUrl(s.photo,560)}" alt="${s.name}" loading="lazy" onerror="this.style.display='none'">`:`<div class="emoji">${s.icon}</div>`;el.innerHTML=`<div class="thumb" style="background:linear-gradient(135deg,${s.color},#45c7f4)">${media}<span class="distance-badge">${fmtDist(s._d)}</span></div><div class="body"><h3>${s.icon} ${s.name}</h3><p>${s.note}</p><div class="mini-meta"><i class="mini-dot" style="background:${s.color}"></i>${s.status||categoryNames[s.category]||s.category}</div></div>`;el.addEventListener('click',()=>openItem(s,s._type,s._type==='route'?route().findIndex(x=>x.id===s.id):-1));box.appendChild(el)});
}
function renderStats(){const steps=Math.round(state.tracked*1.38);$('#stepsHud').textContent=steps.toLocaleString();$('#kmHud').textContent=(state.tracked/1000).toFixed(2);$('#accuracyHud').textContent=state.gps?`±${Math.round(state.gps.acc)}m`:'—';}
function renderHome(){const h=state.home;$('#homeStatus').textContent=`Saved locally: ${h.label} · ${h.lat.toFixed(5)}, ${h.lon.toFixed(5)}`;$('#startMapsBtn').href=mapsDir(`${h.lat},${h.lon}`,'Parque Eduardo VII, Lisboa, Portugal','transit');$('#homeMapsBtn').href=mapsDir('Cais do Sodré, Lisboa, Portugal',`${h.lat},${h.lon}`,'transit');const bt=$('#busTimes');const now=new Date();const n=now.getHours()*60+now.getMinutes();let next=-1;bt.innerHTML='';busRef.forEach(t=>{const m=timeToMin(t)+(timeToMin(t)<360?1440:0),nn=n+(n<360?1440:0);if(next<0&&m>=nn)next=m;const e=document.createElement('span');e.className=`bus-time ${m===next?'next':''}`;e.textContent=t;bt.appendChild(e)});}
function renderPreset(){const e=$('#preset');e.innerHTML=Object.entries(DATA.presets).map(([k,v])=>`<option value="${k}" ${k===state.preset?'selected':''}>${v.label}</option>`).join('');}
function renderCredits(){const used=new Map();[...DATA.route,...DATA.sidequests].forEach(x=>{if(x.photo)used.set(x.photo.source,x.photo)});$('#credits').innerHTML=[...used.values()].map(p=>`<p><a href="${p.source}" target="_blank" rel="noopener">${p.file}</a> — ${p.author}, ${p.license}.</p>`).join('');}
function renderAll(redraw=true){renderCurrent();renderRoute();renderNearby();renderStats();renderHome();if(redraw){drawMap();fitRoute()}else renderMapMarkers();save();}
function openItem(item,type,index){state.selected={item,type,index};$('#sheetName').textContent=item.name;$('#sheetTag').textContent=`${item.icon} ${categoryNames[item.category]||item.category}`;$('#sheetTag').style.background=item.color;$('#sheetNote').textContent=item.note;$('#sheetTip').textContent=item.tip;$('#sheetStatus').textContent=item.status||(type==='side'?'Optional side quest':index===state.current?'Current mission':'Route stop');const d=state.gps?hav(state.gps,item):hav(originForDistance(),item);$('#sheetDistance').textContent=fmtDist(d);$('#sheetMapsBtn').href=mapsDir(state.gps?`${state.gps.lat},${state.gps.lon}`:'My Location',`${item.lat},${item.lon}`,'walking');$('#sheetTargetBtn').textContent=type==='side'?'Navigate to side quest':'Make current target';setImage($('#sheetPhoto'),$('#sheetFallback'),item,true);$('#sheetCredit').innerHTML=item.photo?`Photo: <a href="${item.photo.source}" target="_blank" rel="noopener">${item.photo.author}</a> · ${item.photo.license}`:'Illustrated marker; no landmark photo bundled.';$('#sheetBackdrop').classList.add('open');focusItem(item);}
function closeSheet(){ $('#sheetBackdrop').classList.remove('open'); }
function makeSelectedTarget(){const s=state.selected;if(!s)return;if(s.type==='route'&&s.index>=0){state.current=s.index;closeSheet();renderAll(false);toast(`Mission set: ${s.item.short||s.item.name}`);}else{closeSheet();focusItem(s.item);if(state.gps){if(targetLine)map.removeLayer(targetLine);targetLine=L.polyline([[state.gps.lat,state.gps.lon],[s.item.lat,s.item.lon]],{color:s.item.color,weight:4,dashArray:'8 9'}).addTo(map);}toast(`Side quest highlighted: ${s.item.short||s.item.name}`);}}
function advance(mark=true){const r=route(),t=target();if(mark)state.visited.add(t.id);if(state.current<r.length-1)state.current++;renderAll(false);toast(mark?`Objective cleared — next: ${target().short}`:`Skipped to ${target().short}`);}
function updateGPS(pos){const g={lat:pos.coords.latitude,lon:pos.coords.longitude,acc:pos.coords.accuracy,ts:pos.timestamp,rawHeading:pos.coords.heading,speed:pos.coords.speed};if(state.prev&&g.acc<120&&state.prev.acc<120){const d=hav(state.prev,g),dt=(g.ts-state.prev.ts)/1000;if(d>=2&&d<=Math.max(90,dt*15)){state.tracked+=d;if(Number.isFinite(g.rawHeading))state.heading=g.rawHeading;else if(d>4)state.heading=bearing(state.prev,g);}}state.prev=g;state.gps=g;save();if(map){if(!userMarker){userMarker=L.marker([g.lat,g.lon],{icon:userIcon(),zIndexOffset:2000}).addTo(map);accuracyCircle=L.circle([g.lat,g.lon],{radius:g.acc,color:'#45c7f4',weight:1,fillColor:'#45c7f4',fillOpacity:.12}).addTo(map);}else{userMarker.setLatLng([g.lat,g.lon]).setIcon(userIcon());accuracyCircle.setLatLng([g.lat,g.lon]).setRadius(g.acc);}if(state.follow)map.panTo([g.lat,g.lon],{animate:true,duration:.6});updateTargetLine();}
  const t=target(),d=hav(g,t);if(d<Math.max(45,Math.min(85,g.acc*.7+35))&&Date.now()-state.lastAuto>45000&&state.current<route().length-1){state.lastAuto=Date.now();state.visited.add(t.id);state.current++;navigator.vibrate?.([90,50,90]);toast(`You reached ${t.short}. New mission: ${target().short}`);}
  renderCurrent();renderRoute();renderNearby();renderStats();}
function gpsError(e){const msg={1:'Location denied. Open Chrome → Site settings → Location → Allow, then retry.',2:'Your phone cannot get a location right now.',3:'GPS timed out—move outdoors and retry.'}[e.code]||e.message;toast(msg);$('#gpsBtn').classList.remove('active');}
function toggleGPS(){if(state.watch!==null){navigator.geolocation.clearWatch(state.watch);state.watch=null;$('#gpsBtn').classList.remove('active');toast('GPS paused');return;}if(!navigator.geolocation)return toast('This browser has no geolocation support');state.watch=navigator.geolocation.watchPosition(updateGPS,gpsError,{enableHighAccuracy:true,maximumAge:2500,timeout:20000});$('#gpsBtn').classList.add('active');toast('GPS requested—tap Allow');}
async function enableCompass(){try{if(typeof DeviceOrientationEvent==='undefined')throw new Error('Compass sensor unavailable');if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw new Error('Compass permission denied');}const handler=e=>{let h=e.webkitCompassHeading;if(h==null&&e.absolute&&Number.isFinite(e.alpha))h=(360-e.alpha)%360;if(Number.isFinite(h)){state.heading=h;if(userMarker)userMarker.setIcon(userIcon());$('#compassBtn').classList.add('active')}};window.addEventListener('deviceorientationabsolute',handler,true);window.addEventListener('deviceorientation',handler,true);toast('Compass enabled');}catch(e){toast(`${e.message}. GPS direction still works while moving.`);}}
async function checkPermission(){try{if(!navigator.permissions)return toast('Open Chrome site settings to check Location');const p=await navigator.permissions.query({name:'geolocation'});toast(`Location permission: ${p.state}`);}catch(e){toast('Permission check unavailable; use Chrome site settings.');}}
async function saveOfflinePhotos(){const btn=$('#saveOfflineBtn');btn.disabled=true;btn.textContent='Caching photos…';const urls=[...new Set([...DATA.route,...DATA.sidequests].filter(x=>x.photo).map(x=>photoUrl(x.photo,720)))];let ok=0;for(const u of urls){try{await fetch(u,{mode:'no-cors',cache:'reload'});ok++;btn.textContent=`Saved ${ok}/${urls.length}`}catch(e){}}btn.disabled=false;btn.textContent='Save photos offline';toast(`Loaded ${ok}/${urls.length} landmark photos. Map tiles cache as you view them.`);}
function bind(){
  $('#preset').addEventListener('change',e=>{state.preset=e.target.value;state.current=0;state.visited.clear();renderAll(true)});$('#startTime').addEventListener('change',()=>{renderCurrent();renderRoute()});
  $('#gpsBtn').addEventListener('click',toggleGPS);$('#followBtn').addEventListener('click',()=>{state.follow=!state.follow;$('#followBtn').classList.toggle('active',state.follow);if(state.follow&&state.gps)map?.flyTo([state.gps.lat,state.gps.lon],16);});$('#fitBtn').addEventListener('click',fitRoute);$('#compassBtn').addEventListener('click',enableCompass);
  $('#prevBtn').addEventListener('click',()=>{if(state.current>0){state.current--;renderAll(false)}});$('#arriveBtn').addEventListener('click',()=>advance(true));$('#skipBtn').addEventListener('click',()=>advance(false));$('#nearestBtn').addEventListener('click',()=>{if(!state.gps)return toast('Enable GPS first');const r=route(),b=r.map((x,i)=>({i,d:hav(state.gps,x)})).sort((a,b)=>a.d-b.d)[0];state.current=b.i;renderAll(false);focusItem(r[b.i]);toast(`Nearest route stop: ${r[b.i].short}`)});$('#saveOfflineBtn').addEventListener('click',saveOfflinePhotos);
  $('#detailsBtn').addEventListener('click',()=>openItem(target(),'route',state.current));$('#sheetClose').addEventListener('click',closeSheet);$('#sheetBackdrop').addEventListener('click',e=>{if(e.target===$('#sheetBackdrop'))closeSheet()});$('#sheetTargetBtn').addEventListener('click',makeSelectedTarget);
  $('#setHomeBtn').addEventListener('click',()=>{if(!state.gps)return toast('Enable GPS while at home first');state.home={lat:state.gps.lat,lon:state.gps.lon,label:'My saved GPS home'};renderHome();drawMap();save();toast('Home point saved only on this phone')});$('#targetHomeBtn').addEventListener('click',()=>{if(!map)return;homeMarker.addTo(map);map.flyTo([state.home.lat,state.home.lon],15);toast('Showing saved home')});
  $('#permissionBtn').addEventListener('click',checkPermission);$('#resetBtn').addEventListener('click',()=>{state.current=0;state.tracked=0;state.visited.clear();state.prev=null;renderAll(false);toast('Walk progress reset')});
  const share=async()=>{try{if(navigator.share)await navigator.share({title:'Lisbon Quest Map',text:'Interactive Lisbon walking quest with GPS, photos and non-food detours.',url:location.href});else{await navigator.clipboard.writeText(location.href);toast('Link copied')}}catch(e){}};$('#shareTop').addEventListener('click',share);
  window.addEventListener('online',()=>{$('#offlineBanner').classList.add('hidden');toast('Back online')});window.addEventListener('offline',()=>{$('#offlineBanner').classList.remove('hidden')});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('#installBtn').classList.add('hidden')}});
  const sections=$$('section[id]');const links=$$('.bottom-nav a');const io=new IntersectionObserver(es=>{const top=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(top){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${top.target.id}`))}},{threshold:[.15,.45]});sections.forEach(s=>io.observe(s));
}
function init(){renderPreset();renderCredits();bind();initMap();renderAll(false);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(!navigator.onLine)$('#offlineBanner').classList.remove('hidden');}
init();
