import {DEFAULT_TRAVEL,MODES,normalizeTravel,travelFor,matchesTravel,rangeText,costBadge,euro,uberURL} from './travel.js?v=5.0.0';
import {VERSION,TZ,fmtTime,fmtDate,parts,localAt,distance,distanceText,durationText,mapsURL,searchURL,streetURL,nodesFor,assess,weatherAt,weatherIcon,nearestIndex} from './logic.js?v=5.0.0';
import {icon} from './icons.js?v=5.0.0';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store={get(k,f=null){try{return JSON.parse(localStorage.getItem('wander4-'+k))??f}catch{return f}},set(k,v){try{localStorage.setItem('wander4-'+k,JSON.stringify(v));return true}catch{return false}}};
let D,PH,G,POI,map=null,marker=null,circle=null,watch=null,installEvent=null,saveBusy=false,photoIndex=0,sheetReturn=null,routeMarkers=[],essentialsLayer=null,exploreRoutes=[];
const S={travel:normalizeTravel(store.get('travel',{})),layers:new Set(store.get('layers',['attractions'])),mapStyle:store.get('mapStyle','game'),parked:store.get('parked'),when:store.get('when','now'),mood:'all',search:'',gps:null,gpsWanted:false,weather:store.get('weather'),favorites:new Set(store.get('favorites',[])),progress:store.get('progress',{}),home:store.get('home'),downloads:store.get('downloads',[]),current:null,screen:'explore',lastHash:null};
const safeURL=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)?x.href:'#'}catch{return '#'}};
const btn=(action,label,ico='arrow',cls='outline-button',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${icon(ico)}${label}</button>`;
const link=(url,label,ico='external',cls='outline-button')=>`<a class="${cls}" href="${esc(safeURL(url))}" target="_blank" rel="noopener">${icon(ico)}${label}</a>`;
const img=(key,alt,full=false,eager=false)=>{const p=PH[key];return p?`<img src="./${esc(full?p.src:p.thumb)}" alt="${esc(alt)}" loading="${eager?'eager':'lazy'}" data-thumb="./${esc(p.thumb)}" decoding="async" ${eager?'fetchpriority="high"':''}>`:`<div class="error-photo">Photo unavailable</div>`};
const routeBy=id=>D.routes.find(r=>r.id===id);
const geo=r=>G[r.id]||{legs:[],walkKm:null,verified:false};
const trip=(r,mode=S.travel.mode)=>travelFor(r,D.cities[r.city],{...S.travel,mode});
const score=r=>assess(r,D.cities[r.city],S.weather,S.when,null,new Date(),trip(r).arrivalMinutes);
const photoPlaces=r=>r.stops.map(k=>D.places[k]);
const kmText=r=>r.stops.length===1?'On-site wandering':geo(r).walkKm!=null?`${geo(r).walkKm.toFixed(1)} km${geo(r).verified?'':'+'}`:'Check walking distance';
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function saveState(){store.set('favorites',[...S.favorites]);store.set('progress',S.progress);store.set('when',S.when);store.set('travel',S.travel);store.set('layers',[...S.layers]);store.set('mapStyle',S.mapStyle);}
function connection(){const offline=!navigator.onLine||!!S.networkDown;const e=$('#connection');e.classList.toggle('offline',offline);e.textContent=offline?'Offline':'';}
function credit(key){const p=PH[key];return p?`<p class="credit">Photo: <a href="${esc(safeURL(p.source))}" target="_blank" rel="noopener">${esc(p.author||p.title)}</a> · <a href="${esc(safeURL(p.licenseURL||p.source))}" target="_blank" rel="noopener">${esc(p.license)}</a> · resized / cropped for display.</p>`:'';}
function openSheet(content){sheetReturn=document.activeElement;$('#sheetContent').innerHTML=content;if(!$('#sheet').open)$('#sheet').showModal();$('#sheet').scrollTop=0;$('#closeSheet').focus();}
function closeSheet(){if($('#sheet').open)$('#sheet').close();sheetReturn?.focus?.();}
function currentView(){const raw=location.hash.slice(1);if(!raw)return {page:'explore'};if(raw==='saved'||raw==='plan'||raw==='explore')return {page:raw};const q=new URLSearchParams(raw);if(q.has('walk'))return {page:'walk',id:q.get('walk')};if(q.has('route'))return {page:'route',id:q.get('route')};if(q.has('city'))return {page:'city',id:q.get('city')};return {page:'explore'};}
function disposeMap(){if(map){map.remove();map=null;}marker=null;circle=null;routeMarkers=[];essentialsLayer=null;}
function showTabs(page){$('#bottomTabs').classList.toggle('hidden',page==='route'||page==='walk');$('#actionDock').classList.add('hidden');$$('[data-tab]').forEach(a=>a.classList.toggle('active',a.dataset.tab===page));}
function setDock(html){$('#actionDock').innerHTML=html;$('#actionDock').classList.remove('hidden');}
function heading(title,sub=''){return `<div class="section-heading"><h2>${title}</h2>${sub?`<span class="caption">${sub}</span>`:''}</div>`;}
function whenControl(){return `<label class="when-control">${icon('clock')}<select id="when" aria-label="When you want to leave"><option value="now" ${S.when==='now'?'selected':''}>Leave now</option><option value="morning" ${S.when==='morning'?'selected':''}>Tomorrow morning</option><option value="sunset" ${S.when==='sunset'?'selected':''}>Go for sunset</option></select></label>`;}
function transportControls(){return `<div class="travel-controls"><div class="transport-switch" role="group" aria-label="Travel mode">${Object.entries(MODES).map(([k,m])=>`<button class="mode-button ${S.travel.mode===k?'active':''}" data-action="travelMode" data-value="${k}" aria-pressed="${S.travel.mode===k}">${icon(m.icon)}<span>${m.label}</span></button>`).join('')}</div><div class="limit-row"><label for="travelLimit">${S.travel.mode==='transit'?'Max door-to-start time':'Max time in the car'}<strong id="travelLimitValue">${S.travel.max} min · one way</strong></label>${btn('travelSettings','Budget & buffer','settings','text-button')}</div><input id="travelLimit" aria-label="Maximum one-way travel minutes" type="range" min="15" max="240" step="15" value="${S.travel.max}"><div class="limit-presets">${[30,45,60,90,120,180].map(n=>`<button data-action="travelMax" data-value="${n}" class="${S.travel.max===n?'active':''}">${n>=60?n/60+'h':n+'m'}</button>`).join('')}</div><p class="caption">From the 2660-213 area · ${S.travel.mode==='transit'?'estimated connections, not live departures':`includes ${S.travel.buffer}% driving buffer; parking / last leg shown separately`}.</p></div>`;}
function travelPill(r){const t=trip(r);return `<span class="travel-pill ${t.borderline?'edge':''}">${icon(MODES[t.mode].icon)}${rangeText(t.range)}${t.borderline?' · borderline':''}</span>`;}
function card(r,{featured=false}={}){const a=score(r),city=D.cities[r.city],t=trip(r);if(featured)return `<a class="featured" href="#route=${r.id}" aria-label="Explore ${esc(r.title)}">${img(r.hero,r.title,true,true)}<div class="featured-content"><span class="tag">${icon(a.tone==='good'?'sun':'clock')}${esc(a.label)}</span><h2>${esc(r.title)}</h2><p>${esc(city.name)} · ${esc(r.subtitle)}</p><div class="feature-stats"><span>${icon('clock')}${durationText(r.visitHours)} outing</span><span>${icon('walk')}${kmText(r)}</span>${a.weather?.temp!=null?`<span>${weatherIcon(a.weather.code,a.day)} ${Math.round(a.weather.temp)}° on arrival</span>`:''}</div>${travelPill(r)}<span class="featured-cta">${icon('arrow')}</span></div></a>`;
return `<a class="route-card" href="#route=${r.id}" aria-label="Explore ${esc(r.title)}"><div class="card-image">${img(r.hero,r.title)}<span class="tag">${icon(r.when.includes('night')?'moon':'sun')}${esc(a.label)}</span></div><div class="card-copy"><div class="eyebrow">${esc(city.name)} · ${esc(r.moods.slice(0,2).join(' / '))}</div><h3>${esc(r.title)}</h3><p><span>${durationText(r.visitHours)} outing</span><span>${kmText(r)}</span></p>${travelPill(r)}<p class="travel-price">${costBadge(t)}</p></div></a>`;}
function layerControls(){const layers=[['attractions','pin','Sights'],['toilets','toilet','Toilets'],['water','water','Water'],['rest','leaf','Rest'],['parking','car','Parking'],['food','food','Food'],['pharmacy','medical','Pharmacy']];return `<div class="map-layers" role="group" aria-label="Map layers">${layers.map(([k,ic,n])=>`<button data-action="layer" data-value="${k}" class="${S.layers.has(k)?'active':''}" aria-pressed="${S.layers.has(k)}">${icon(ic)}${n}</button>`).join('')}</div>`;}
function explorerMapHTML(){return `<section class="map-card explorer-card"><div class="map-head"><div><strong>Your escape radius</strong><p class="caption">Tap a destination. Zoom in for local essentials.</p></div><div class="map-controls">${btn('mapStyle','','map','icon-button','aria-label="Toggle game or street map style"')}${btn('fit','','expand','icon-button','aria-label="Fit destinations"')}${btn('locate','','locate','icon-button','aria-label="Show my location"')}</div></div>${layerControls()}<div id="explorerMap" role="region" aria-label="Map of matching trips and useful places"></div><div id="mapWarning" class="map-note ${navigator.onLine?'hidden':''}">Offline: saved places remain; street tiles need data.</div><div class="map-caption"><span>◉ matching trips</span><span id="poiCount">Select an essentials layer</span></div><p class="caption map-data-note">Mapped facilities may be closed, paid or incomplete. No fabricated reviews or “open now” claims.</p></section>`;}
function renderExplore(cityId=null,saved=false){const city=D.cities[cityId];let all=D.routes.filter(r=>(!city||r.city===city.id)&&(!saved||S.favorites.has(r.id))&&(S.mood==='all'||r.moods.includes(S.mood)));if(S.search){const q=S.search.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');all=all.filter(r=>`${r.title} ${D.cities[r.city].name} ${r.subtitle}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(q));}let rs=all.filter(r=>matchesTravel(trip(r),S.travel));rs.sort((a,b)=>score(b).score-score(a).score);exploreRoutes=rs;
const moods=[['all','All moods','map'],['quiet','Peaceful','leaf'],['water','Water / breeze','wave'],['fantasy','Storybook','castle'],['night','After dark','moon']];let body=`<div class="page"><div class="intro"><div><div class="eyebrow">WANDER 5 · FIND YOUR NEXT WORLD</div><h1>${saved?'Keep the good ones.':city?esc(city.name)+', differently.':'Pick your escape.'}</h1><p>${saved?'Your saved trips, with your current travel filter.':'Choose your ride. Set your limit.'}</p></div>${whenControl()}</div>${city?`<a class="back" href="#explore">${icon('back')}All destinations</a>`:''}${transportControls()}<div class="explorer-search"><label>${icon('search')}<input id="destinationSearch" type="search" value="${esc(S.search)}" placeholder="Find a place or atmosphere" aria-label="Search destinations"></label><span>${rs.length} / ${all.length} walks</span></div><div class="filter-row">${moods.map(([id,n,ic])=>`<button class="pill ${S.mood===id?'active':''}" data-action="mood" data-value="${id}" aria-pressed="${S.mood===id}">${icon(ic)}${n}</button>`).join('')}</div>${explorerMapHTML()}`;
if(rs.length){body+=`${heading('Fits your journey budget',`${rs.length} matching walks`)}<div class="home-top">${card(rs[0],{featured:true})}${rs.length>1?`<div class="route-grid">${rs.slice(1,3).map(r=>card(r)).join('')}</div>`:''}</div>`;if(rs.length>3)body+=`<div class="route-grid more-trips">${rs.slice(3).map(r=>card(r)).join('')}</div>`;}else body+=`<div class="empty">${icon('clock')}<h2>No matching trips at ${S.travel.max} minutes.</h2><p>We haven’t quietly ignored your limit. Try 90 minutes, a different mode or a wider radius.</p>${btn('travelMax','Try 90 minutes','clock','solid-button','data-value="90"')}</div>`;
body+=`<div class="filter-foot"><label><input id="borderline" type="checkbox" ${S.travel.showBorderline?'checked':''}> Include borderline trips</label><p class="caption">Off by default. A trip must fit at the cautious end of its estimate.</p></div>`;
if(!city&&!saved){const visibleCities=Object.values(D.cities).filter(c=>rs.some(r=>r.city===c.id));body+=`${heading('Pick a landscape',`${visibleCities.length} places within your filter`)}<div class="city-grid">${visibleCities.map(c=>`<a class="city-card" href="#city=${c.id}">${img(c.hero,c.name)}<strong>${esc(c.name)}</strong></a>`).join('')}</div>`;}body+=`<p class="help-line">${icon('info')}<span>Travel and spending numbers are planning estimates from Loures, not live routes or bookings. Weather is assessed for the expected arrival. ${S.home?'Your saved home changes navigation, not the Loures-based filter.':''}</span></p><div class="route-footer">${btn('sources','Data & photo credits','photo')}${btn('travelSettings','Adjust assumptions','settings')}</div></div>`;$('#main').innerHTML=body;initExplorerMap(rs);}
function weatherPanel(r){const a=score(r),w=a.weather;return `<div class="weather-score"><span class="weather-symbol">${weatherIcon(w?.code,a.day)}</span><div><strong>${esc(a.label)}</strong><p>${esc(D.cities[r.city].name)} · arrival ~${fmtTime(a.arrival)}</p></div></div><div class="weather-details">${w?`<span>${Math.round(w.temp)}°C</span><span>Feels ${Math.round(w.feels??w.temp)}°</span><span>${w.rain??'—'}% rain</span><span>${Math.round(w.wind??0)} km/h wind</span>`:'<span>Forecast unavailable — no weather assumed.</span>'}</div><p class="weather-time">${fmtDate(a.arrival)} · ${w?`Open-Meteo forecast · ${w.stale?'cached':'updated'} ${fmtTime(new Date(w.fetched))}`:'Daylight-based suggestion only'}${!navigator.onLine?' · offline':''}</p><p class="advice ${a.tone==='good'?'good':''}">${esc(a.reason)}</p><div class="daylight-badge">${icon(MODES[S.travel.mode].icon)}~${durationText(Math.round(a.travel/5)*5/60)} to start · planning estimate</div>${w?.sunset?`<div class="daylight-badge">${icon('sunset')}Sunset ${fmtTime(new Date(w.sunset))}</div>`:''}${photoPlaces(r).some(p=>p.ticket)?'<p class="caption">Daylight does not mean gates are open. Check today’s tickets and last entry.</p>':''}<button class="mini-link" data-action="conditions">Time, weather & access ${icon('chevron')}</button>`;}
function mapHTML(r){return `<div class="map-card"><div class="map-head"><strong>Your whole journey</strong><div class="map-controls"><button class="icon-button" data-action="mapStyle" aria-label="Toggle game or street map style">${icon('map')}</button><button class="icon-button" data-action="fit" aria-label="Show full journey">${icon('expand')}</button><button class="icon-button" data-action="locate" aria-label="Show my location">${icon('locate')}</button></div></div>${layerControls()}<div id="journeyMap" class="journey-map" role="region" aria-label="Interactive full route map for ${esc(r.title)}"></div><div id="mapWarning" class="map-note ${navigator.onLine?'hidden':''}">Offline map: route and pins remain; street tiles need a connection.</div><div class="map-caption"><span><i></i>${r.stops.length===1?'Visitor area':'Walking preview'}</span>${r.transfers.length?'<span><i class="transit"></i>Transport transfer</span>':''}<span>Tap a numbered stop</span></div></div>`;}
function renderRoute(r){S.current=r;const favorite=S.favorites.has(r.id),places=photoPlaces(r),g=geo(r);document.title=`${r.title} · Wander`;
 $('#main').innerHTML=`<div class="page route-page"><div class="route-tools"><a class="back" href="#city=${r.city}">${icon('back')}${esc(D.cities[r.city].name)}</a><div>${btn('favorite','', 'save','icon-button',`aria-label="${favorite?'Unsave':'Save'} walk" aria-pressed="${favorite}"`)}${btn('share','','share','icon-button','aria-label="Share this walk"')}</div></div><section class="hero">${img(r.hero,r.title,true,true)}<button class="hero-source" data-action="heroPhoto">${icon('photo')} Real place photo</button><div class="hero-copy"><div class="eyebrow">${esc(D.cities[r.city].name)}, Portugal</div><h1>${esc(r.title)}</h1><p>${esc(r.subtitle)}</p></div></section><div class="photo-strip" aria-label="Photos of the different stops">${places.filter(p=>p.photo!==r.hero).map(p=>`<button data-action="place" data-id="${p.id}" aria-label="View ${esc(p.name)}">${img(p.photo,p.name)}<span>${esc(p.name)}</span></button>`).join('')}</div><div class="route-meta"><div>${icon('clock')}<span>${durationText(r.visitHours)}<small>including visits</small></span></div><div>${icon('walk')}<span>${kmText(r)}<small>${r.stops.length===1?'choose signed paths on site':'mapped walking'}</small></span></div><div>${icon('route')}<span>${esc(r.terrain)}<small>${r.transfers.length?'includes transfers':`${r.stops.length} places to discover`}</small></span></div></div>${tripSummary(r)}<div class="route-layout">${mapHTML(r)}<aside class="side-card" id="conditionsPanel">${weatherPanel(r)}</aside></div>${heading('What you’ll see',`${places.length} different places`)}<div class="stop-list">${places.map((p,i)=>`<button class="stop-card" data-action="place" data-id="${p.id}"><div class="stop-photo">${img(p.photo,p.name)}<span class="stop-marker">${i+1}</span></div><div class="stop-copy"><strong>${esc(p.name)}</strong><p>${esc(p.cue)}</p>${p.ticket?'<span class="ticket-chip">Interior / grounds may need tickets</span>':''}</div></button>`).join('')}</div><div class="route-footer">${btn('transport','Getting there & home','train')}${btn('saveOffline',S.downloads.includes(r.id)?'Saved offline':'Save this walk','download')}${btn('join','Join near me','locate')}${btn('detours','Nearby ideas','map')}</div><p class="help-line">${icon('info')}<span>${esc(r.caution)}</span></p><p class="caption" style="margin-top:12px">${r.stops.length===1?'This map shows the visitor area, not an invented full internal trail. Follow the open signed paths on site.':g.verified?'Walking lines follow mapped pedestrian paths, not compass bearings.':'Some legs are unverified and shown dashed.'} Signs, gates and temporary closures always take priority. Google Maps may choose a different accessible path.</p><div class="route-footer">${btn('gpx','Export route outline','download')}${btn('sources','Sources & credits','photo')}</div></div>`;
 setDock(`${btn('start',S.progress[r.id]?'Continue walk':'Start walk','play','solid-button')}${btn('transport','Get there',MODES[S.travel.mode].icon,'outline-button')}`);initMap(r);
}
function progressFor(r){const ns=nodesFor(r,D.places);let v=S.progress[r.id]||{i:0,done:[],started:Date.now()};v.i=Math.max(0,Math.min(Number(v.i)||0,ns.length-1));if(!Array.isArray(v.done))v.done=[];return v;}
function renderFocus(r){S.current=r;const ns=nodesFor(r,D.places),pr=progressFor(r);S.progress[r.id]=pr;saveState();const n=ns[pr.i],leg=geo(r).legs.find(l=>l.end===n.id),transfer=leg?.mode==='transit'||(r.transfers||[]).some(t=>(Array.isArray(t)?t[1]:t.to)===n.id);const completed=pr.complete===true;const done=pr.done.length;
 document.title=`${n.name} · Wander`;
 if(completed){$('#main').innerHTML=`<div class="page focus-page"><a class="back" href="#route=${r.id}">${icon('back')}Whole journey</a><div class="empty" style="margin-top:24px">${icon('check')}<h1>Well wandered.</h1><p>${esc(r.title)}<br>${done} stops marked · ${kmText(r)} mapped route</p>${btn('transport','Find my way home','home','solid-button')}<div class="route-footer">${btn('restart','Walk again','undo')}<a class="outline-button" href="#explore">Explore more</a></div></div></div>`;setDock(btn('transport','Journey home','home','solid-button'));return;}
 const initialLeg=pr.i===0&&pr.done.length===0&&(!S.gps||distance(S.gps,n)>500);const transportLeg=initialLeg||transfer;const legMode=transportLeg?(S.travel.mode==='transit'?'transit':'driving'):'walking';const nav=mapsURL(n,legMode);
 $('#main').innerHTML=`<div class="page focus-page"><div class="focus-heading"><a class="back" href="#route=${r.id}">${icon('back')}Whole journey</a><p>${pr.i+1} / ${ns.length}</p></div><div class="progress" aria-label="Route progress"><div style="width:${Math.round(pr.i/ns.length*100)}%"></div></div><div class="focus-card">${n.anchor?`<div class="anchor-art">${icon(n.id==='finish'?'home':'train')}<span>${n.id==='finish'?'RETURN POINT':'START POINT'}</span></div>`:img(n.photo,n.name,true,true)}<span class="tag">${icon(transfer?'train':n.anchor?'pin':'walk')}${transfer?'Transport transfer':n.anchor?(n.id==='finish'?'The finish':'Get to the start'):'Your next place'}</span>${!n.anchor?btn('place','','photo','icon-button photo-open',`data-id="${n.id}" aria-label="Photo and details of ${esc(n.name)}"`):''}</div><div class="focus-title"><h1>${esc(n.name)}</h1><p>${esc(n.cue)}</p></div><p id="focusStatus" class="focus-status">${S.gps?`${distanceText(distance(S.gps,n))} straight-line proximity · GPS ±${Math.round(S.gps.acc)} m`:'No compass guessing. Maps handles the actual streets.'}</p><div class="focus-note">${icon(transfer?'train':'headphones')}<span><strong>${initialLeg?'Get to the start using your selected transport.':transfer?'Use the transport link for this leg.':'Open Maps, tap Start, then put the phone away.'}</strong><br>${initialLeg?'Already at the start? Tap “I’m here” below.':transfer?'This gap is not marked as a walking route.':'Come back here at the landmark and tap “I’m here”.'}${!navigator.onLine?' Google walking / transit directions need data.':''}</span></div><div class="focus-controls">${btn('previous','Back','back','outline-button',pr.i===0?'disabled':'')}${btn('arrived',n.id==='finish'?'Finish walk':'I’m here','check','solid-button')}${btn('skip','Skip','arrow','outline-button')}</div><div class="focus-linkbar">${btn('join','Join nearby','locate','text-button')}${btn('transport','Home / transit','home','text-button')}${btn('locate','My position','locate','text-button')}${btn('essentials','Toilets / water','toilet','text-button')}${S.travel.mode==='car'?btn('returnCar','Find my car','car','text-button'):''}</div><p class="caption" style="margin-top:18px">Maps guides one leg at a time. Wander does not monitor you or announce turns while your phone is locked.</p></div>`;
 setDock(link(nav,`<span class="button-label">${initialLeg?'Get to the walk start':transfer?'Find transport':'Navigate with Google Maps'}<small>${transportLeg?(S.travel.mode==='transit'?'Public transport planner':S.travel.mode==='car'?'Driving route · check legal parking':'Driving preview · Uber / Bolt quotes in trip options'):'Walking directions · one leg at a time'}</small></span>`,transportLeg?MODES[S.travel.mode].icon:'play','solid-button'));
}
function renderPlan(){const eligible=D.routes.filter(r=>matchesTravel(trip(r),S.travel)).sort((a,b)=>score(b).score-score(a).score);const seen=new Set(),plan=[];for(const r of eligible){if(!seen.has(r.city)){seen.add(r.city);plan.push(r);}if(plan.length===5)break;}$('#main').innerHTML=`<div class="page"><div class="intro"><div><div class="eyebrow">A MIX, NOT A MARCH</div><h1>Make each day<br>feel different.</h1><p>Five ideas using your travel mode and time limit. Swap for weather, closures and energy.</p></div></div>${transportControls()}<div class="plan-list">${plan.map((r,i)=>`<article class="plan-card">${img(r.hero,r.title)}<div class="plan-copy"><div class="eyebrow">IDEA ${i+1} · ${esc(D.cities[r.city].name)}</div><h2>${esc(r.title)}</h2><p>${esc(r.subtitle)}</p>${travelPill(r)}<a href="#route=${r.id}">See this walk ${icon('arrow')}</a></div></article>`).join('')}</div>${plan.length<5?'<p class="small-notice">Fewer than five destinations match. Increase the time allowance to see more—not the same place five times.</p>':''}</div>`;}
function render(keepScroll=false){if(!D)return;const v=currentView();const previousScroll=scrollY;disposeMap();S.screen=v.page;S.current=null;showTabs(v.page);document.title='Wander · Portugal, on foot';if(v.page==='route'||v.page==='walk'){const r=routeBy(v.id);if(r){v.page==='route'?renderRoute(r):renderFocus(r);}else{location.hash='explore';return;}}else if(v.page==='plan')renderPlan();else renderExplore(v.page==='city'?v.id:null,v.page==='saved');if(keepScroll)scrollTo(0,previousScroll);else scrollTo({top:0,behavior:'instant'});connection();}
function initMap(r){if(!window.L){$('#journeyMap').innerHTML='<div class="error-photo">Map could not load. The stop list and Google Maps buttons still work.</div>';return;}map=L.map('journeyMap',{scrollWheelZoom:false,zoomControl:false,minZoom:5,maxZoom:19});L.control.zoom({position:'bottomleft'}).addTo(map);const tiles=addBaseTiles(map);let errors=0;
 tiles.on('tileerror',()=>{if(++errors>=2){const e=$('#mapWarning');if(e){e.textContent='Street background unavailable. The route and place pins still work.';e.classList.remove('hidden');}}});
 const geometry=geo(r);geometry.legs.forEach(l=>{const walking=l.mode==='walk';if(l.points?.length>1){L.polyline(l.points,{color:walking?'#fff':'#536faf',weight:walking?8:3,opacity:1,dashArray:walking?null:'6 7'}).addTo(map);if(walking)L.polyline(l.points,{color:'#f4438d',weight:4,opacity:.94}).addTo(map);}});
 if(!geometry.legs.length)L.polyline([r.start,...photoPlaces(r),r.end].map(p=>[p.lat,p.lon]),{color:'#536faf',weight:3,dashArray:'6 8'}).addTo(map);
 photoPlaces(r).forEach((p,i)=>{const m=L.marker([p.lat,p.lon],{icon:L.divIcon({className:'',html:`<span class="stop-marker">${i+1}</span>`,iconSize:[29,29],iconAnchor:[14,14]}),title:p.name,zIndexOffset:100+i}).addTo(map).on('click',()=>placeSheet(p.id));routeMarkers.push(m);});
 const anchor=(p,text)=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:'',html:`<span class="anchor-marker">${text}</span>`,iconSize:[85,30],iconAnchor:[-12,32]}),zIndexOffset:-50}).addTo(map).bindPopup(esc(p.name));
 anchor(r.start,distance(r.start,r.end)<40?'Start / finish':'Start');if(distance(r.start,r.end)>=40)anchor(r.end,'Finish');fitMap();updateMapGPS(false);map.on('moveend',drawEssentials);drawEssentials();
}
function fitMap(){if(!map)return;if(!S.current){fitExplorer();return;}const r=S.current;const pts=geo(r).legs.flatMap(l=>l.points||[]);pts.push([r.start.lat,r.start.lon],[r.end.lat,r.end.lon],...photoPlaces(r).map(p=>[p.lat,p.lon]));map.fitBounds(L.latLngBounds(pts),{padding:[35,35],maxZoom:16,animate:false});setTimeout(()=>map?.invalidateSize(),120);}
function updateMapGPS(pan=false){if(!map||!S.gps)return;const g=S.gps;if(!marker){marker=L.marker([g.lat,g.lon],{icon:L.divIcon({className:'',html:'<span class="puck"></span>',iconSize:[18,18],iconAnchor:[9,9]}),zIndexOffset:1000,title:'Your position'}).addTo(map);circle=L.circle([g.lat,g.lon],{radius:Math.min(g.acc,500),color:'#1d6ee0',weight:1,fillOpacity:.08}).addTo(map);}else{marker.setLatLng([g.lat,g.lon]);circle.setLatLng([g.lat,g.lon]).setRadius(Math.min(g.acc,500));}if(pan)map.setView([g.lat,g.lon],16);}
function placeSheet(id){const p=D.places[id];if(!p)return;const r=S.current;const i=r?.stops.indexOf(id);if(map&&i>=0){routeMarkers.forEach((m,n)=>m.setZIndexOffset(n===i?600:100+n));}
 openSheet(`${img(p.photo,p.name,true,true).replace('<img ','<img class="sheet-image" ')}<div class="sheet-body"><div class="eyebrow">${r&&i>=0?`STOP ${i+1} · `:''}${p.ticket?'CHECK TICKETS / ACCESS':'A PLACE TO PAUSE'}</div><h2 id="sheetTitle">${esc(p.name)}</h2><p><strong>${esc(p.cue)}</strong></p><p>${esc(p.about)}</p><div class="sheet-actions">${btn('photo','Full photograph','photo','outline-button',`data-key="${p.photo}" data-name="${esc(p.name)}"`)}${link(streetURL(p),'Look around in Street View','map')}</div><div class="sheet-actions">${r?btn('chooseStop','Make this my next stop','pin','solid-button',`data-id="${p.id}"`):''}${link(searchURL(`${p.name}, Portugal`),'Place in Maps','external')}</div>${p.source?`<a class="source-link" href="${esc(safeURL(p.source))}" target="_blank" rel="noopener">Official visitor information</a>`:''}${credit(p.photo)}</div>`);
}
function photoSheet(key,name='Photograph'){openSheet(`<div>${img(key,name,true,true).replace('<img ','<img class="sheet-fullphoto" ')}</div><div class="sheet-body"><h2 id="sheetTitle">${esc(name)}</h2>${credit(key)}</div>`);}
function conditionsSheet(){const r=S.current;if(!r)return;const a=score(r);openSheet(`<div class="sheet-body"><h2 id="sheetTitle">A good time to go?</h2>${whenControl()}<div style="margin-top:18px">${weatherPanel(r).replace(/<button class="mini-link"[\s\S]*?<\/button>/,'')}</div><div class="small-notice">${esc(r.caution)}</div><p>Arrival and outing times are planning estimates, not live transit or opening-hours guarantees. Weather is for ${esc(D.cities[r.city].name)}, not your phone’s location.</p>${link(r.source||D.cities[r.city].links[0][1],'Check current access','external')}<a class="source-link" href="https://open-meteo.com/" target="_blank" rel="noopener">Weather: Open-Meteo, CC BY 4.0</a></div>`);}
function transportSheet(){const r=S.current||routeBy(exploreRoutes[0]?.id)||D.routes[0],c=D.cities[r.city],h=S.home||{text:'2660-213 Santo António dos Cavaleiros, Portugal'},home=h.text||`${h.lat},${h.lon}`,t=trip(r);const mode=S.travel.mode==='transit'?'transit':'driving';openSheet(`<div class="sheet-body"><div class="eyebrow">THE WHOLE OUTING, NOT JUST THE FIRST LEG</div><h2 id="sheetTitle">${esc(c.name)} · there & back</h2><div class="transport-switch">${Object.entries(MODES).map(([k,m])=>`<button class="mode-button ${S.travel.mode===k?'active':''}" data-action="sheetMode" data-value="${k}">${icon(m.icon)}${m.label}</button>`).join('')}</div>${tripSummary(r,true)}<h3>Getting there</h3>${S.travel.mode==='transit'?c.there.map(x=>`<div class="transport-step"><p>${esc(x)}</p></div>`).join(''):`<p>Route to <strong>${esc(r.start.name)}</strong>. Check legal parking and the final approach, not just the pin.</p>${r.carAccess?`<div class="small-notice">${esc(r.carAccess)}</div>`:''}`}
<div class="sheet-actions">${link(mapsURL(r.start,mode,null,false),'Directions from me',MODES[S.travel.mode].icon,'solid-button')}${link(mapsURL(r.start,mode,home,false),'From saved home','home')}${S.travel.mode==='ride'?`${link(uberURL(r.start),'Get Uber quote','ride')}${link('https://bolt.eu/en/rider/','Open Bolt / get quote','ride')}`:''}</div>
${S.travel.mode==='car'?`<div class="car-return-box"><h3>${icon('car')} Don’t strand the car</h3><p>${r.returnToCar?'This route finishes away from its start. Allow time to return to your parking spot.':'This outing returns near its start. Save the actual parking spot, not the attraction pin.'}</p><div class="sheet-actions">${btn('parkGPS','Save where I parked','locate','solid-button')}${btn('returnCar','Walk back to car','car')}</div><p class="caption">Parking coordinates stay only on your device.</p></div>`:''}
<h3>Coming home</h3>${c.back.map(x=>`<div class="transport-step"><p>${esc(x)}</p></div>`).join('')}<div class="sheet-actions">${link(mapsURL(home,mode,null,false),'Route home now','home','solid-button')}${link(mapsURL(r.end,'walking'),'Walk to return point','walk')}</div>${S.travel.mode==='ride'?`<p class="small-notice">${t.rural?'Rural pickup may be unavailable. Confirm a return ride before committing.':'Check a separate return quote; the outward fare does not guarantee the fare home.'} This app cannot see Uber/Bolt availability, surge or bookings.</p>`:''}<p class="caption">Home: ${esc(h.text||h.label||'Your saved location')}. Shared route links never contain your home or parked car.</p><div class="detail-list">${c.links.map(([n,u])=>`<a href="${esc(safeURL(u))}" target="_blank" rel="noopener">${esc(n)} ${icon('external')}</a>`).join('')}</div>${btn('travelSettings','Edit fuel, costs & buffer','settings')}</div>`);}
function detoursSheet(){const r=S.current||routeBy('lisbon-classic');const near=Object.values(D.places).filter(p=>!r.stops.includes(p.id)&&distance(p,r.start)<17000).sort((a,b)=>distance(a,r.start)-distance(b,r.start)).slice(0,5);
 openSheet(`<div class="sheet-body"><div class="eyebrow">ONLY IF THE MOOD TAKES YOU</div><h2 id="sheetTitle">A little further</h2><p>Optional ideas, not extra compulsory stops. Check access and your return before detouring.</p>${r.extra?`<div class="small-notice">${esc(typeof r.extra==='string'?r.extra:r.extra?.trailNote||'')}</div>`:''}<div class="detail-list">${near.map(p=>`<button data-action="detourPlace" data-id="${p.id}"><span>${esc(p.name)}<br><small class="muted">${esc(p.cue)}</small></span>${icon('chevron')}</button>`).join('')}</div>${r.city==='lisbon'?`<h3>Something completely different</h3><div class="detail-list"><a href="https://zenius-i-vanisher.com/v5.2/arcade.php?id=8795&section=summary" target="_blank" rel="noopener"><span>Four-arrow dance arcade<br><small class="muted">Tropical Time · community listing, verify cabinet first</small></span>${icon('external')}</a><a href="https://ra.co/events/pt/lisbon" target="_blank" rel="noopener"><span>Electronic music tonight<br><small class="muted">Current listings, not a cached “live” event</small></span>${icon('external')}</a></div>`:''}</div>`);
}
function settingsSheet(){const h=S.home;openSheet(`<div class="sheet-body"><div class="eyebrow">WANDER ${VERSION}</div><h2 id="sheetTitle">Make it yours.</h2><div class="detail-list"><button data-action="travelSettings"><span>Transport, journey time & costs</span>${icon('car')}</button><button data-action="essentials"><span>Toilets, water, parking & useful places</span>${icon('toilet')}</button><button data-action="install"><span>Install / add to home screen</span>${icon('download')}</button><button data-action="locate"><span>Allow my location</span>${icon('locate')}</button><button data-action="sources"><span>Photo credits & sources</span>${icon('photo')}</button></div><label class="home-field">Your home / return area<input id="homeInput" type="text" maxlength="200" placeholder="Postcode, town or station" value="${esc(h?.text||'2660-213 Santo António dos Cavaleiros, Portugal')}"></label><div class="sheet-actions">${btn('saveHome','Save home','check','solid-button')}${btn('homeGPS','Use GPS here','locate')}</div><p class="caption">Home, favourites and progress stay in this browser. No account or analytics. Map and weather providers receive normal requests; opening Maps sends your chosen destination to Google.</p><h3>Phone down, honestly.</h3><p>Wander shows the places and the complete route. Google Maps speaks directions for each leg after you tap Start there. Return to Wander at each landmark. This browser app does not give locked-screen turn-by-turn directions.</p><h3>Offline</h3><p>Saved walk photos, place cards and route outlines work offline. Street-map backgrounds, fresh weather, live transport and Google Maps walking directions still need a connection. GPS also requires device permission.</p><p class="caption">Keep one ear aware of traffic and your surroundings. A charged phone and a checked return matter more than a step target.</p><div class="detail-list"><button data-action="refreshWeather">Refresh weather ${icon('cloud')}</button><button data-action="clearDownloads">Remove saved photo downloads ${icon('download')}</button></div></div>`);}
function sourcesSheet(){const r=S.current;const keys=[...new Set(r?[r.hero,...photoPlaces(r).map(p=>p.photo)]:Object.keys(PH))];openSheet(`<div class="sheet-body"><h2 id="sheetTitle">Real places. Real photographs.</h2><p>Photos are stored with the app, not fragile external image links. All are credited below. They show the named places, but are not live images.</p>${r?`<a class="source-link" href="${esc(safeURL(r.source))}" target="_blank" rel="noopener">Visitor information for this walk</a>`:''}<p class="caption">Mapped routes: OpenStreetMap contributors; pedestrian route geometry prepared with Valhalla / FOSSGIS OSRM. Changes to paths, closures and gates must be checked locally. Travel durations and visit durations are estimates.</p><a class="source-link" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap copyright</a><a class="source-link" href="https://open-meteo.com/" target="_blank" rel="noopener">Weather: Open-Meteo</a><p class="caption">Travel: planning ranges, not live timetables. Fuel: editable DGEG national reference dated ${esc(D.fuel.date)}. Ride budgets are illustrative arithmetic, not provider fares. Useful-place pins: OpenStreetMap snapshot ${esc(POI.fetched||'unavailable')}; incomplete and not live status.</p><a class="source-link" href="${esc(D.fuel.source)}" target="_blank" rel="noopener">DGEG fuel source</a>${keys.map(k=>`<h3>${esc(PH[k]?.title||k)}</h3>${credit(k)}`).join('')}</div>`);}
async function getGPS(){if(!navigator.geolocation)throw Error('Location is unavailable in this browser. Manual stops and Maps still work.');return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,acc:p.coords.accuracy,time:p.timestamp}),e=>reject(Error(e.code===1?'Location denied. Allow Location in Chrome site settings, or choose your stop manually.':e.code===3?'Location timed out. Try outdoors, or choose your stop manually.':'Location unavailable. Manual navigation still works.')),{enableHighAccuracy:true,timeout:15000,maximumAge:10000}));}
function onGPS(g){S.gps=g;updateMapGPS(false);const status=$('#focusStatus');if(status&&S.current){const ns=nodesFor(S.current,D.places),n=ns[progressFor(S.current).i];status.textContent=`${distanceText(distance(g,n))} straight-line proximity · GPS ±${Math.round(g.acc)} m`;}}
function startWatch(){if(watch!==null||!S.gpsWanted||document.hidden||!navigator.geolocation)return;watch=navigator.geolocation.watchPosition(p=>onGPS({lat:p.coords.latitude,lon:p.coords.longitude,acc:p.coords.accuracy,time:p.timestamp}),()=>{stopWatch();S.gpsWanted=false;},{enableHighAccuracy:true,maximumAge:12000,timeout:20000});}
function stopWatch(){if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null;}}
async function locate(){try{toast('Finding your position…');const g=await getGPS();onGPS(g);S.gpsWanted=true;startWatch();if(map)updateMapGPS(true);else if(['explore','city','saved'].includes(S.screen))render(true);toast(`Location ready · accuracy ±${Math.round(g.acc)} m`);}catch(e){toast(e.message);}}
async function join(){if(!S.current)return;try{toast('Finding a sensible starting point…');const g=await getGPS();onGPS(g);const ns=nodesFor(S.current,D.places),best=nearestIndex(ns,g);if(best.m>15000)throw Error('You are not near this walk yet. Use Get there first.');if(g.acc>150)throw Error('Location is too imprecise. Choose the stop manually from the map.');const n=ns[best.i];openSheet(`<div class="sheet-body"><h2 id="sheetTitle">Join at ${esc(n.name)}?</h2><p>${distanceText(best.m)} straight-line proximity. This skips earlier stops only after you confirm.</p><div class="sheet-actions">${btn('joinConfirm','Start here','check','solid-button',`data-index="${best.i}"`)}${btn('close','Keep my place','back')}</div></div>`);}catch(e){toast(e.message);}}
function chooseIndex(i){const r=S.current,ns=nodesFor(r,D.places),pr=progressFor(r);pr.i=Math.max(0,Math.min(i,ns.length-1));pr.complete=false;S.progress[r.id]=pr;saveState();closeSheet();if(S.screen==='walk')render(true);else location.hash=`walk=${r.id}`;}
function advance(skip=false){const r=S.current,ns=nodesFor(r,D.places),pr=progressFor(r);if(!skip&&!pr.done.includes(ns[pr.i].id))pr.done.push(ns[pr.i].id);if(pr.i===ns.length-1)pr.complete=true;else pr.i++;S.progress[r.id]=pr;saveState();render();}
async function downloadWalk(){const r=S.current;if(!r||saveBusy)return;if(!navigator.onLine){toast('Connect once to save this walk’s photos.');return;}if(!('caches'in window)){toast('Offline saving is not supported here.');return;}saveBusy=true;const keys=[...new Set([r.hero,...photoPlaces(r).map(p=>p.photo)])];const urls=keys.flatMap(k=>PH[k]?[PH[k].src,PH[k].thumb]:[]);openSheet(`<div class="sheet-body"><h2 id="sheetTitle">Save the whole picture.</h2><p id="downloadStatus">Saving ${urls.length} images for ${esc(r.title)}…</p><div class="offline-progress"><div id="downloadProgress" style="width:0"></div></div><p class="caption">Place cards and route outlines are also saved. Street maps and Google navigation are not downloaded.</p></div>`);let good=0;
 try{const cache=await caches.open('wander4-photos-v1');for(const rel of urls){const url=new URL(rel,location.href).href;const hit=await cache.match(url);if(!hit){const resp=await fetch(url);if(!resp.ok||!resp.headers.get('content-type')?.startsWith('image/'))throw Error('An image could not be saved. Retry while connected.');await cache.put(url,resp);}good++;if($('#downloadProgress'))$('#downloadProgress').style.width=`${Math.round(good/urls.length*100)}%`;}
  if(!('serviceWorker'in navigator))throw Error('Offline reopening needs a supported HTTPS browser.');await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('App cache is still installing. Retry saving in a moment.')),30000))]);
  if(!S.downloads.includes(r.id))S.downloads.push(r.id);store.set('downloads',S.downloads);if($('#downloadStatus'))$('#downloadStatus').textContent='Ready offline: photos, place cards and route outline.';toast('Walk saved for offline browsing.');
 }catch(e){if($('#downloadStatus'))$('#downloadStatus').textContent=e.message;toast(e.message);}finally{saveBusy=false;}
}
function exportGPX(){const r=S.current;if(!r)return;const g=geo(r);let xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Wander" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${esc(r.title)}</name><desc>Pedestrian preview. Transport gaps are separate; obey local access restrictions.</desc></metadata>`;photoPlaces(r).forEach(p=>xml+=`<wpt lat="${p.lat}" lon="${p.lon}"><name>${esc(p.name)}</name></wpt>`);xml+=`<trk><name>${esc(r.title)}</name>`;g.legs.filter(l=>l.mode==='walk').forEach(l=>{xml+='<trkseg>'+l.points.map(([lat,lon])=>`<trkpt lat="${lat}" lon="${lon}"/>`).join('')+'</trkseg>';});xml+='</trk></gpx>';const u=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));const a=document.createElement('a');a.href=u;a.download=`wander-${r.id}.gpx`;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
async function refreshWeather(force=false){if(!navigator.onLine)return;if(!force&&S.weather&&Date.now()-S.weather.fetched<1800000&&Object.keys(D.cities).every(k=>S.weather.data?.[k]))return;const cities=Object.values(D.cities);const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',cities.map(c=>c.lat).join(','));u.searchParams.set('longitude',cities.map(c=>c.lon).join(','));u.searchParams.set('hourly','temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m');u.searchParams.set('daily','sunrise,sunset');u.searchParams.set('timezone',TZ);u.searchParams.set('timeformat','unixtime');u.searchParams.set('forecast_days','7');
 try{const res=await fetch(u,{signal:AbortSignal.timeout(10000)});if(!res.ok)throw Error('Forecast not available');let data=await res.json();if(!Array.isArray(data))data=[data];const bundle={fetched:Date.now(),data:{}};cities.forEach((c,i)=>{if(!data[i]?.hourly?.time)throw Error('Incomplete forecast');bundle.data[c.id]=data[i];});S.weather=bundle;store.set('weather',bundle);if(['explore','city','saved'].includes(S.screen))render(true);else if(S.screen==='route'&&$('#conditionsPanel'))$('#conditionsPanel').innerHTML=weatherPanel(S.current);if(force)toast('Forecast updated.');
 }catch{if(force)toast('Weather unavailable. No weather is assumed.');}
}
async function share(){const u=new URL(location.href);u.search='';u.hash=S.current?`route=${S.current.id}`:'explore';try{if(navigator.share)await navigator.share({title:S.current?.title||'Wander Portugal',url:u.href});else{await navigator.clipboard.writeText(u.href);toast('Route link copied. Private home details are not shared.');}}catch(e){if(e.name!=='AbortError')openSheet(`<div class="sheet-body"><h2 id="sheetTitle">Share this walk</h2><label class="home-field">Copy this link<input readonly value="${esc(u.href)}" onclick="this.select()"></label></div>`);}}
async function install(){if(installEvent){await installEvent.prompt();installEvent=null;return;}openSheet(`<div class="sheet-body"><h2 id="sheetTitle">Keep Wander on your phone.</h2><p><strong>Android Chrome:</strong> open the browser menu, then choose <strong>Install app</strong> or <strong>Add to Home screen</strong>.</p><p><strong>iPhone Safari:</strong> Share → Add to Home Screen.</p><p>Open it online once. Save a walk to keep its photos offline. Maps still handles directions separately.</p></div>`);}
async function actions(e){const el=e.target.closest('[data-action]');if(!el)return;const act=el.dataset.action,r=S.current;
 switch(act){
 case 'travelMode':S.travel.mode=el.dataset.value;saveState();render(true);break;
 case 'sheetMode':S.travel.mode=el.dataset.value;saveState();transportSheet();break;
 case 'travelMax':S.travel.max=Number(el.dataset.value);saveState();render(true);break;
 case 'travelSettings':travelSettingsSheet();break;
 case 'saveTravel':saveTravelSettings();break;case 'reloadUpdate':location.reload();break;
 case 'layer':S.layers.has(el.dataset.value)?S.layers.delete(el.dataset.value):S.layers.add(el.dataset.value);saveState();$$(`[data-action="layer"][data-value="${el.dataset.value}"]`).forEach(b=>{b.classList.toggle('active',S.layers.has(el.dataset.value));b.setAttribute('aria-pressed',String(S.layers.has(el.dataset.value)));});drawEssentials();break;
 case 'mapStyle':S.mapStyle=S.mapStyle==='game'?'street':'game';saveState();render(true);break;
 case 'poi':poiSheet(el.dataset.id);break;
 case 'essentials':essentialsSheet();break;
 case 'parkGPS':try{const g=await getGPS();S.parked={lat:g.lat,lon:g.lon,saved:Date.now(),route:S.current?.id};store.set('parked',S.parked);toast('Parking spot saved only on this device.');}catch(e){toast(e.message);}break;
 case 'returnCar':returnCarSheet();break;
 case 'copyPlace':try{await navigator.clipboard.writeText(`${S.current.start.name}, ${S.current.start.lat}, ${S.current.start.lon}`);toast('Walk start copied for your ride app.');}catch{toast('Open the route details to copy the start name.');}break;

 case 'mood':S.mood=el.dataset.value;render(true);break;
 case 'favorite':if(!r)return;if(S.favorites.has(r.id))S.favorites.delete(r.id);else S.favorites.add(r.id);saveState();el.setAttribute('aria-pressed',String(S.favorites.has(r.id)));el.setAttribute('aria-label',S.favorites.has(r.id)?'Unsave walk':'Save walk');el.style.color=S.favorites.has(r.id)?'var(--purple)':'';toast(S.favorites.has(r.id)?'Saved to your walks.':'Removed from saved walks.');break;
 case 'start':if(r){if(!S.progress[r.id])S.progress[r.id]={i:0,done:[],started:Date.now()};saveState();location.hash=`walk=${r.id}`;}break;
 case 'place':case 'detourPlace':placeSheet(el.dataset.id);break;
 case 'photo':photoSheet(el.dataset.key,el.dataset.name);break;
 case 'heroPhoto':if(r)photoSheet(r.hero,photoPlaces(r).find(p=>p.photo===r.hero)?.name||r.title);break;
 case 'chooseStop':if(r){const ns=nodesFor(r,D.places);chooseIndex(ns.findIndex(n=>n.id===el.dataset.id));}break;
 case 'arrived':advance();break;case 'skip':advance(true);break;
 case 'previous':if(r){chooseIndex(Math.max(0,progressFor(r).i-1));}break;
 case 'restart':if(r){S.progress[r.id]={i:0,done:[],started:Date.now()};saveState();render();}break;
 case 'joinConfirm':chooseIndex(Number(el.dataset.index));break;
 case 'transport':transportSheet();break;case 'conditions':conditionsSheet();break;
 case 'share':await share();break;case 'install':await install();break;
 case 'locate':await locate();break;case 'join':await join();break;case 'fit':fitMap();break;
 case 'saveOffline':await downloadWalk();break;case 'gpx':exportGPX();break;
 case 'sources':sourcesSheet();break;case 'detours':detoursSheet();break;case 'close':closeSheet();break;
 case 'saveHome':{const v=$('#homeInput')?.value.trim();if(!v){toast('Enter a postcode, town or station.');return;}S.home={text:v};store.set('home',S.home);toast('Home saved only on this device.');break;}
 case 'homeGPS':try{const g=await getGPS();S.home={lat:g.lat,lon:g.lon,label:'My private saved location'};store.set('home',S.home);toast('Home saved privately from GPS.');}catch(err){toast(err.message);}break;
 case 'refreshWeather':await refreshWeather(true);break;
 case 'clearDownloads':await caches.delete('wander4-photos-v1');S.downloads=[];store.set('downloads',[]);toast('Saved full-size photos removed; basic app cache retained.');break;
 }
}
function bind(){document.addEventListener('click',actions);document.addEventListener('input',e=>{if(e.target.id==='travelLimit')$('#travelLimitValue').textContent=`${e.target.value} min · one way`;if(e.target.id==='destinationSearch'){S.search=e.target.value;clearTimeout(bind.searchTimer);bind.searchTimer=setTimeout(()=>{const p=e.target.selectionStart;render(true);const x=$('#destinationSearch');x?.focus();x?.setSelectionRange?.(p,p);},550);}});
 document.addEventListener('change',e=>{if(e.target.id==='travelLimit'){S.travel.max=Number(e.target.value);saveState();render(true);}if(e.target.id==='fuelTypeInput'){$('#fuelInput').value=D.fuel[e.target.value]||D.fuel.petrol;}if(e.target.id==='borderline'){S.travel.showBorderline=e.target.checked;saveState();render(true);}});
$('#menuButton').innerHTML=icon('menu');$('#menuButton').addEventListener('click',settingsSheet);$('#closeSheet').addEventListener('click',closeSheet);$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)closeSheet();}});
 document.addEventListener('change',e=>{if(e.target.id==='when'){S.when=e.target.value;saveState();const wasSheet=$('#sheet').open;render(true);if(wasSheet&&S.current)conditionsSheet();}});
 document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement&&e.target.hasAttribute('data-thumb')&&!e.target.dataset.failed){if(e.target.dataset.thumb&&!e.target.dataset.fallback&&e.target.src!==new URL(e.target.dataset.thumb,location.href).href){e.target.dataset.fallback='1';e.target.src=e.target.dataset.thumb;return;}e.target.dataset.failed='1';const f=document.createElement('span');f.className='error-photo';f.textContent='Photo unavailable · retry online';e.target.replaceWith(f);}},true);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stopWatch();else startWatch();});
 window.addEventListener('hashchange',()=>{closeSheet();render();});window.addEventListener('online',()=>{checkNetwork();refreshWeather();});window.addEventListener('offline',()=>{connection();const note=$('#mapWarning');if(note)note.classList.remove('hidden');});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});
 $$('.bottom-tabs a').forEach(a=>{const which={explore:'map',saved:'save',plan:'calendar'}[a.dataset.tab];a.innerHTML=icon(which)+a.textContent;});
}
function tripSummary(r,inSheet=false){const t=trip(r),f=D.fuel;return `<section class="trip-summary ${t.fits?'':'outside'}"><div class="trip-top"><span class="trip-icon">${icon(MODES[t.mode].icon)}</span><div><strong>${rangeText(t.range)} ${t.mode==='transit'?'to the start':'in the car'}</strong><p>${t.mode==='transit'?'Door-to-start estimate from Loures':`+ about ${t.lastMile} min for parking / final approach`}</p></div><span class="budget-tag">${t.fits?'FITS YOUR LIMIT':t.supported?'OVER YOUR LIMIT':'NEEDS A LAST-LEG RIDE'}</span></div><div class="trip-money">${t.mode==='car'?`<b>${euro(t.carFuel)}</b><span>return fuel / car<br>${t.unknownExtras?'+ tolls & parking not yet entered':`${euro(t.carTotal)} including your entered extras`} · ${euro(t.perPerson)} / person${t.unknownExtras?' before unknown extras':''}</span>`:t.mode==='transit'?`<b>${euro(t.publicFare[0])}–${euro(t.publicFare[1])}</b><span>rough return allowance / person<br>not a ticket quote; passes and regional fares vary</span>`:`<b>${euro(t.ride[0])}–${euro(t.ride[1])}</b><span>one-way illustrative ride budget<br>not a live Uber/Bolt quote · return priced separately</span>`}</div>${inSheet?`<details class="cost-detail"><summary>How these numbers work</summary>${t.mode==='car'?`<p>${t.km.toFixed(1)} km each way × 2 × ${S.travel.consumption} L/100 km × €${S.travel.fuelPrice.toFixed(3)}/L. Fuel only between Loures and the walk start. Local transfers, detours and driving back to a differently parked car can add distance.</p><p>Reference ${esc(f.date)}: national average, not your pump. Consumption, fuel price, people and round-trip extras are editable.</p>`:t.mode==='ride'?`<p>Budget model: €${S.travel.rideBase} + €${S.travel.rideKm}/km + €${S.travel.rideMinute}/minute; an illustrative 1–1.7× range. This is not an operator rate card. Live fares, waiting time, tolls and surge may differ substantially.</p>`:`<p>Broad planning range for a return day trip from Loures, including local access where straightforward. Attraction tickets and private last-mile rides are excluded. No departure or final connection has been reserved.</p>`}<p>Driving estimates include your ${S.travel.buffer}% traffic buffer. ${t.roadSource?'Road distance/time: precomputed OpenStreetMap routing, without live traffic.':'Road time and distance are planning estimates.'} No estimate can guarantee an arrival time.</p></details>`:btn('transport','Compare & plan the return','arrow','text-button')}${r.carAccess&&t.mode!=='transit'?`<p class="small-notice">${esc(r.carAccess)}</p>`:''}${r.extra?.trailNote?`<p class="caption">${esc(r.extra.trailNote)}</p>`:''}</section>`;}
function travelSettingsSheet(){openSheet(`<div class="sheet-body"><div class="eyebrow">YOUR COMFORT · YOUR BUDGET</div><h2 id="sheetTitle">Make the estimates yours.</h2><p>The trip filter always uses the approximate 2660-213 base. Saved home and GPS still work for navigation from wherever you are.</p><div class="settings-grid"><label>Traffic buffer, %<input id="bufferInput" type="number" min="0" max="60" step="5" value="${S.travel.buffer}"></label><label>People sharing the car<input id="peopleInput" type="number" min="1" max="8" value="${S.travel.people}"></label><label>Fuel<select id="fuelTypeInput"><option value="petrol" ${S.travel.fuelType==='petrol'?'selected':''}>Petrol 95</option><option value="diesel" ${S.travel.fuelType==='diesel'?'selected':''}>Diesel</option></select></label><label>Price, €/litre<input id="fuelInput" type="number" min="0.1" max="5" step="0.001" value="${S.travel.fuelPrice}"></label><label>Consumption, L/100 km<input id="consumptionInput" type="number" min="2" max="25" step="0.1" value="${S.travel.consumption}"></label><label>Round-trip tolls, €<input id="tollsInput" type="number" min="0" step="0.1" placeholder="Unknown" value="${S.travel.tolls??''}"></label><label>Parking total, €<input id="parkingInput" type="number" min="0" step="0.1" placeholder="Unknown" value="${S.travel.parking??''}"></label></div><p class="caption">Fuel defaults: DGEG national daily reference ${esc(D.fuel.date)}. Update to your actual pump price. Blank extras remain unknown—not zero-cost promises.</p>${link(D.fuel.source,'Check fuel prices','external','text-button')}<details class="cost-detail"><summary>Ride budget model · optional</summary><p>Not a live Uber/Bolt quote. This is only a planning calculator; check the actual app before setting off.</p><div class="settings-grid"><label>Base, €<input id="rideBaseInput" type="number" min="0" max="50" step="0.1" value="${S.travel.rideBase}"></label><label>€/km<input id="rideKmInput" type="number" min="0" max="10" step="0.05" value="${S.travel.rideKm}"></label><label>€/minute<input id="rideMinuteInput" type="number" min="0" max="3" step="0.05" value="${S.travel.rideMinute}"></label></div></details><div class="sheet-actions">${btn('saveTravel','Save assumptions','check','solid-button')}</div></div>`);}
function saveTravelSettings(){const n=id=>Number($(id).value),maybe=id=>$(id).value===''?null:n(id);S.travel=normalizeTravel({...S.travel,buffer:n('#bufferInput'),people:n('#peopleInput'),fuelType:$('#fuelTypeInput').value,fuelPrice:n('#fuelInput'),consumption:n('#consumptionInput'),tolls:maybe('#tollsInput'),parking:maybe('#parkingInput'),rideBase:Math.max(0,n('#rideBaseInput')),rideKm:Math.max(0,n('#rideKmInput')),rideMinute:Math.max(0,n('#rideMinuteInput'))});saveState();closeSheet();render(true);toast('Travel comfort and budgets updated.');}
function addBaseTiles(m){m.getPane('tilePane').style.filter=S.mapStyle==='game'?'grayscale(1) invert(.92) contrast(.82) brightness(.9)':'';return L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,keepBuffer:1,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}).addTo(m);}
function initExplorerMap(rs){if(!window.L)return;map=L.map('explorerMap',{scrollWheelZoom:false,zoomControl:false,minZoom:6,maxZoom:19});L.control.zoom({position:'bottomleft'}).addTo(map);const tiles=addBaseTiles(map);let errors=0;tiles.on('tileerror',()=>{if(++errors>2)$('#mapWarning')?.classList.remove('hidden');});const grouped=new Map();rs.forEach(r=>{if(!grouped.has(r.city))grouped.set(r.city,[]);grouped.get(r.city).push(r);});for(const [id,walks]of grouped){const c=D.cities[id],r=walks[0],t=trip(r);const html=`<span class="world-pin">${icon(r.moods.includes('water')?'wave':r.moods.includes('fantasy')?'castle':'pin')}<b>${Math.round(t.range[1])}m</b></span>`;const mk=L.marker([r.start.lat,r.start.lon],{icon:L.divIcon({className:'',html,iconSize:[58,52],iconAnchor:[29,45]}),title:`${c.name}: ${rangeText(t.range)}`}).addTo(map);mk.bindPopup(`<div class="map-destination">${img(r.hero,c.name)}<strong>${esc(c.name)}</strong><small>${rangeText(t.range)} · ${esc(MODES[S.travel.mode].label)}</small>${walks.slice(0,3).map(x=>`<a href="#route=${x.id}">${esc(x.title)} →</a>`).join('')}</div>`,{maxWidth:260,minWidth:210});}
L.marker([D.home.lat,D.home.lon],{icon:L.divIcon({className:'',html:'<span class="base-pin">⌂</span>',iconSize:[30,30],iconAnchor:[15,15]}),title:'Loures planning base'}).addTo(map).bindPopup('Approximate 2660-213 base. Journey budgets begin here.');fitExplorer();map.on('moveend',drawEssentials);drawEssentials();updateMapGPS(false);}
function fitExplorer(){if(!map)return;const pts=[[D.home.lat,D.home.lon],...exploreRoutes.map(r=>[r.start.lat,r.start.lon])];if(pts.length===1)map.setView(pts[0],11);else map.fitBounds(L.latLngBounds(pts),{padding:[40,35],maxZoom:13,animate:false});setTimeout(()=>map?.invalidateSize(),100);}
const amenityIcons={toilets:'toilet',water:'water',rest:'leaf',parking:'car',food:'food',pharmacy:'medical',attractions:'pin'};
const amenityColors={toilets:'#49d6fa',water:'#43b6ff',rest:'#81df92',parking:'#b9bdcc',food:'#ffb45a',pharmacy:'#ff8198',attractions:'#c18bff'};
const amenities=()=>[...(POI?.items||[]),...(D.pickedFood||[]).map(p=>({...p,kind:'food',curated:true}))];
function drawEssentials(){if(!map)return;if(!essentialsLayer)essentialsLayer=L.layerGroup().addTo(map);essentialsLayer.clearLayers();const z=map.getZoom(),b=map.getBounds().pad(.08);const inView=p=>b.contains([p.lat,p.lon]);let count=0;if(z>=12&&S.layers.has('attractions')){Object.values(D.places).filter(p=>inView(p)&&!S.current?.stops.includes(p.id)).forEach(p=>{L.marker([p.lat,p.lon],{icon:L.divIcon({className:'',html:'<span class="essential-pin sight-pin">✦</span>',iconSize:[24,24],iconAnchor:[12,12]}),title:p.name}).addTo(essentialsLayer).on('click',()=>placeSheet(p.id));count++;});}
if(z>=12){const center=map.getCenter();const list=amenities().filter(p=>S.layers.has(p.kind)&&inView(p)).sort((a,b)=>(b.curated?1:0)-(a.curated?1:0)||distance(a,{lat:center.lat,lon:center.lng})-distance(b,{lat:center.lat,lon:center.lng})).slice(0,140);for(const p of list){L.marker([p.lat,p.lon],{icon:L.divIcon({className:'',html:`<span class="essential-pin ${p.curated?'picked-pin':''}" style="--pin-color:${amenityColors[p.kind]||'#ddd'}">${icon(amenityIcons[p.kind]||'pin')}</span>`,iconSize:[28,28],iconAnchor:[14,14]}),title:p.name}).addTo(essentialsLayer).on('click',()=>poiSheet(p.id));count++;}}const e=$('#poiCount');if(e)e.textContent=z<12?'Zoom in for toilets, water & food':`${count} mapped places shown`;}
function poiSheet(id){const p=amenities().find(x=>x.id===id);if(!p)return;const kind=p.kind||'pin';openSheet(`<div class="sheet-body"><div class="poi-sheet-icon" style="--pin-color:${amenityColors[kind]}">${icon(amenityIcons[kind])}</div><div class="eyebrow">${esc(kind)} · ${p.curated?'CURATED IDEA':'MAPPED FACILITY'}</div><h2 id="sheetTitle">${esc(p.name)}</h2>${p.badge?`<span class="picked-badge">${esc(p.badge)}${p.price?' · '+esc(p.price):''}</span>`:''}<p>${esc(p.note||'A mapped point, not a guarantee of access or current operation.')}</p><div class="poi-facts"><span>Hours: <b>${esc(p.hours||'not recorded')}</b></span><span>Fee: <b>${esc(p.fee||'unknown')}</b></span><span>Access: <b>${esc(p.access||'check on arrival')}</b></span>${p.wheelchair?`<span>Wheelchair: <b>${esc(p.wheelchair)}</b></span>`:''}</div><div class="sheet-actions">${link(mapsURL(p,'walking'),'Walk there','walk','solid-button')}${link(searchURL(`${p.name}, ${p.lat},${p.lon}`),p.kind==='food'?'Reviews / menu / hours':'Check map details','external')}</div><p class="caption">${p.kind==='water'?'Only points tagged as drinking water are shown. Check local signs; fountains are not automatically drinking water.':p.kind==='toilets'?'A toilet may be paid, inside a building or unavailable overnight. A blank hours field does not mean open.':p.kind==='food'?'No star rating or “open now” status is invented. Guide-listed does not mean Michelin-starred; use the reviews / menu link for current detail.':'Opening, accessibility and parking rules can change.'}</p>${link(p.source||'https://www.openstreetmap.org/','Source record','external','text-button')}<p class="caption">${p.curated?'Selection source checked during this build.':`OpenStreetMap snapshot ${esc(POI.fetched||'unknown')}. Coverage is incomplete.`}</p></div>`);}
function essentialsSheet(){const o=S.gps||S.current?.start||D.home;const near=amenities().filter(p=>distance(o,p)<5000&&p.kind!=='food').sort((a,b)=>distance(o,a)-distance(o,b)).slice(0,16);openSheet(`<div class="sheet-body"><div class="eyebrow">A LITTLE LESS TO THINK ABOUT</div><h2 id="sheetTitle">Useful places nearby</h2><p>${S.gps?'Near your last foreground GPS fix.':S.current?'Near the walk start. Enable GPS for your actual position.':'Near the Loures planning base.'} Distances below are straight-line proximity, not walking distances.</p><div class="detail-list">${near.map(p=>`<button data-action="poi" data-id="${esc(p.id)}"><span>${icon(amenityIcons[p.kind]||'pin')}${esc(p.name)}<small>${esc(p.kind)} · ${distanceText(distance(o,p))} · hours ${esc(p.hours||'unknown')}</small></span>${icon('chevron')}</button>`).join('')}</div>${!near.length?'<p>No mapped facilities in this small area. That means missing data, not no facilities.</p>':''}<div class="sheet-actions">${link(searchURL(`public toilets near ${o.lat},${o.lon}`),'Search toilets','toilet')}${link(searchURL(`drinking water near ${o.lat},${o.lon}`),'Search drinking water','water')}</div></div>`);}
function returnCarSheet(){const p=S.parked,r=S.current;const dest=p||r?.start;if(!dest){toast('Save your parking point or open a walk first.');return;}openSheet(`<div class="sheet-body"><h2 id="sheetTitle">${p?'Your saved parking spot':'Back to the walk start'}</h2><p>${p?`Saved ${fmtDate(new Date(p.saved))} at ${fmtTime(new Date(p.saved))}. Confirm this is the car you parked today.`:'No parking point saved. This link leads to the walk start, not a guessed car location.'}</p>${link(mapsURL(dest,'walking'),'Walking directions','car','solid-button')}<p class="caption">Do not begin driving directions until you are back at the vehicle. Parked coordinates are not included when sharing.</p></div>`);}

async function init(){try{[D,PH,G,POI]=await Promise.all(['catalog.json','photos.json','geometry.json','pois.json'].map(async f=>{const r=await fetch('./'+f);if(!r.ok)throw Error(`Could not load ${f}`);return r.json();}));bind();render();refreshWeather();checkNetwork();
 if('serviceWorker'in navigator){const hadController=!!navigator.serviceWorker.controller;navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{reg.update().catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!hadController)return;const bar=document.createElement('div');bar.className='update-bar';bar.innerHTML='<span>New app ready. Keep your place.</span><button data-action="reloadUpdate">Refresh</button>';if(!document.querySelector('.update-bar'))document.body.appendChild(bar);});}).catch(()=>{});}
 window.Wander={version:VERSION,data:D,photos:PH,geometry:G,pois:POI,state:S,render,trip,fitMap,assess:(id,selection='now',now=new Date())=>assess(routeBy(id),D.cities[routeBy(id).city],S.weather,selection,null,now,trip(routeBy(id)).arrivalMinutes)};
 }catch(err){$('#main').innerHTML=`<div class="page"><div class="empty">${icon('info')}<h1>Let’s reconnect.</h1><p>The first load needs a connection. Nothing has been lost.</p><button class="solid-button" onclick="location.reload()">Try again</button></div></div>`;console.error(err);}}

init();

async function checkNetwork(){try{const r=await fetch("./connectivity.txt?t="+Date.now(),{cache:"no-store",signal:AbortSignal.timeout(4500)});if(!r.ok)throw Error();S.networkDown=false;}catch(_){S.networkDown=true;}connection();}
