// Planning models only. These functions never claim a live fare or timetable.
export const DEFAULT_TRAVEL={mode:'transit',max:90,buffer:20,consumption:6.5,fuelType:'petrol',fuelPrice:2.022,people:1,tolls:null,parking:null,rideBase:2.5,rideKm:.85,rideMinute:.15,showBorderline:false};
export const MODES={transit:{label:'Public only',icon:'train'},car:{label:'My car',icon:'car'},ride:{label:'Uber / Bolt',icon:'ride'}};
const finite=(n,f)=>Number.isFinite(Number(n))?Number(n):f;
export function normalizeTravel(v={}){const t={...DEFAULT_TRAVEL,...v};if(!MODES[t.mode])t.mode='transit';t.max=Math.max(15,Math.min(240,finite(t.max,90)));t.buffer=Math.max(0,Math.min(60,finite(t.buffer,20)));t.consumption=Math.max(2,Math.min(25,finite(t.consumption,6.5)));t.fuelPrice=Math.max(.1,Math.min(5,finite(t.fuelPrice,2.022)));t.people=Math.max(1,Math.min(8,Math.round(finite(t.people,1))));for(const [k,ceiling] of [['rideBase',50],['rideKm',10],['rideMinute',3]])t[k]=Math.max(0,Math.min(ceiling,finite(t[k],DEFAULT_TRAVEL[k])));for(const k of ['tolls','parking'])t[k]=t[k]===null||t[k]===''?null:Math.max(0,finite(t[k],0));return t;}
export const euro=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:n<10?2:0}).format(n);
export function travelFor(r,c,input={}){const t=normalizeTravel(input),o={...c.travelOptions,...r.travelOptions};let drive=Math.max(1,o.driveMinutes||60),km=Math.max(.1,o.km||30);const driveLow=Math.round(drive),driveHigh=Math.ceil(drive*(1+t.buffer/100));const lastMile=o.parkingMin??10;const carFuel=2*km*t.consumption/100*t.fuelPrice;const extras=(t.tolls??0)+(t.parking??0);const fare=(o.publicBudget||[0,0]).map(Number);const rideLow=Math.ceil(t.rideBase+km*t.rideKm+drive*t.rideMinute),rideHigh=Math.ceil(rideLow*1.7);const range=t.mode==='transit'?(o.transit||[c.travel,c.travel+20]):[driveLow,driveHigh];const supported=t.mode!=='transit'||o.publicSuitable!==false;const fits=supported&&range[1]<=t.max;const borderline=supported&&!fits&&range[0]<=t.max;return {mode:t.mode,label:MODES[t.mode].label,range,limit:t.max,fits,borderline,supported,km,driveLow,driveHigh,lastMile,arrivalMinutes:t.mode==='transit'?range[1]:driveHigh+lastMile,carFuel,carTotal:carFuel+extras,perPerson:(carFuel+extras)/t.people,unknownExtras:t.tolls===null||t.parking===null,publicFare:fare,ride:[rideLow,rideHigh],rural:!!o.rural,roadSource:o.roadSource||null,roadDate:o.roadDate||null};}
export function matchesTravel(tr,t){return tr.fits||Boolean(t.showBorderline&&tr.borderline);}
export const rangeText=r=>`${Math.round(r[0])}–${Math.round(r[1])} min`;
export function costBadge(tr){if(tr.mode==='transit')return `${euro(tr.publicFare[0])}–${euro(tr.publicFare[1])} return allowance`;if(tr.mode==='car')return `${euro(tr.carFuel)} return fuel`;return `${euro(tr.ride[0])}–${euro(tr.ride[1])} / ride model`;}
export function uberURL(point){const u=new URL('https://m.uber.com/ul/');u.searchParams.set('action','setPickup');u.searchParams.set('pickup','my_location');u.searchParams.set('dropoff[latitude]',point.lat);u.searchParams.set('dropoff[longitude]',point.lon);u.searchParams.set('dropoff[nickname]',point.name||'Walk start');u.searchParams.set('dropoff[formatted_address]',point.name||'Portugal');return u.href;}
