from pathlib import Path
import json, shutil
P=Path('staging');shutil.copytree('wander4',P,dirs_exist_ok=True)
d=json.loads((P/'catalog.json').read_text());photos={}
base={'lisbon':(17,25,[45,80],[6,12]),'sintra':(34,35,[85,125],[10,22]),'cascais':(44,40,[95,140],[10,20]),'almada':(34,40,[75,110],[9,18]),'tomar':(122,80,[150,205],[20,36]),'coimbra':(191,120,[160,220],[35,85]),'obidos':(74,50,[80,120],[16,28]),'evora':(144,95,[155,210],[25,50])}
for cid,c in d['cities'].items():
 km,drive,trans,cost=base[cid];c['travelOptions']={'km':km,'driveMinutes':drive,'transit':trans,'publicBudget':cost,'publicSuitable':True,'parkingMin':10,'rural':False};c['travel']=trans[1]
def place(k,name,lat,lon,cue,about,source,query,ticket=False,close=None):
 d['places'][k]={'id':k,'name':name,'lat':lat,'lon':lon,'photo':k,'cue':cue,'about':about,'source':source,'ticket':ticket,'dwell':20}
 if close:d['places'][k]['closeHour']=close
 photos[k]={'query':query,'expected':name,'lat':lat,'lon':lon}
def city(k,name,lat,lon,hero,tag,km,drive,trans,cost,there,back,source,public=True,rural=False):
 d['cities'][k]={'id':k,'name':name,'lat':lat,'lon':lon,'hero':hero,'tag':tag,'travel':trans[1],'there':there,'back':back,'links':[['Visitor information',source],['Live journey planner','https://www.google.com/maps/'],['Local buses','https://www.carrismetropolitana.pt/']],'travelOptions':{'km':km,'driveMinutes':drive,'transit':trans,'publicBudget':cost,'publicSuitable':public,'parkingMin':10,'rural':rural}}
def route(k,cid,title,sub,stops,hours,moods,terrain,when,caution,source,transfers=None,start=None,extra=None):
 ps=[d['places'][x] for x in stops];anchor=lambda p:{x:p[x] for x in ['name','lat','lon']}
 d['routes'].append({'id':k,'city':cid,'title':title,'subtitle':sub,'stops':stops,'hero':ps[0]['photo'],'start':start or anchor(ps[0]),'end':start or anchor(ps[0]),'visitHours':hours,'moods':moods,'terrain':terrain,'when':when,'caution':caution,'source':source,'transfers':transfers or [],'extra':extra or '', 'new':True})
V='https://www.visitlisboa.com/en/regions/ericeira'
place('ericeira-town','Ericeira old town',38.9633,-9.4171,'White lanes above a bright Atlantic horizon.','Wander the old fishing village and public coastal paths, with short stops rather than a beach day.',V,'Ericeira village coast')
place('ericeira-pescadores','Praia dos Pescadores viewpoint',38.9657,-9.4176,'Fishing boats and the beach below the village.','Look from the public viewpoint. Going onto the sand is optional.',V,'Praia dos Pescadores Ericeira')
place('ericeira-sebastiao','São Sebastião coastal viewpoint',38.9710,-9.4187,'A small chapel above an open sweep of coast.','Stay on maintained paths and away from unstable cliff edges.',V,'Capela São Sebastião Ericeira')
city('ericeira','Ericeira',38.964,-9.416,'ericeira-town','White lanes, surf and Atlantic light',38,32,[80,120],[12,22],['Regional bus via Campo Grande / Mafra to Ericeira terminal.','Use a current journey planner; this is not a direct Lisbon train trip.'],['Check the regional return before a late sunset walk.'],V,rural=True)
route('ericeira','ericeira','Atlantic light, without the beach day','Fishing-village lanes and coastal viewpoints',['ericeira-town','ericeira-pescadores','ericeira-sebastiao'],3,['water','quiet','views'],'Town lanes and promenade',['day','sunset'],'Stay on the signed public paths. Strong winds can make exposed edges unpleasant.',V)
V='https://www.visitlisboa.com/en/regions/mafra'
place('mafra-palace','National Palace of Mafra',38.9367,-9.3265,'A monumental facade with a very different scale.','The exterior makes a good short stop; the famous library and palace interiors need tickets and opening-hour checks.',V,'Palácio Nacional de Mafra facade',True)
place('mafra-cerco','Jardim do Cerco',38.9378,-9.3268,'Formal gardens immediately beside the palace.','A calmer green complement to the stone facade. Check garden gates and hours.',V,'Jardim do Cerco Mafra')
city('mafra','Mafra',38.937,-9.328,'mafra-palace','Royal scale and quiet gardens',27,26,[70,105],[10,18],['Regional bus towards Mafra from Campo Grande.','Check the palace-area stop, not simply the municipality.'],['Check the next bus before leaving the gardens.'],V)
route('mafra','mafra','Royal scale, garden calm','A palace-and-garden outing close to the base',['mafra-palace','mafra-cerco'],3,['oldworld','quiet'],'Mostly level town and garden',['day'],'Palace interiors and garden gates have their own hours; buy only the ticket you actually want.',V)
V='https://tapadademafra.pt/'
place('tapada','Tapada Nacional de Mafra',38.9705,-9.2933,'Forest tracks and space to breathe.','Choose a signed visitor trail at the managed entrance. Do not treat this entrance pin as an unrestricted forest trail.',V,'Tapada Nacional de Mafra forest',True)
city('tapada','Tapada de Mafra',38.9705,-9.2933,'tapada','Managed woodland and wildlife',30,31,[110,155],[12,24],['Mafra town transport does not necessarily reach the visitor entrance.','A last-leg ride may be needed.'],['Book or confirm a pickup before entering the forest.'],V,public=False,rural=True)
route('tapada','tapada','A proper woodland escape','Choose a signed trail and leave the city behind',['tapada'],3,['quiet','fantasy'],'Managed woodland paths',['day'],'Opening hours, fire restrictions and visitor access must be checked directly. No after-dark forest routing.',V,extra={'trailNote':'The map shows the visitor entrance; choose the open signed trail on site.'})
V='https://visitsintra.travel/'
place('azenhas','Azenhas do Mar viewpoint',38.8411,-9.4621,'A white village cascading towards the ocean.','The viewpoint gives the classic postcard angle. The village steps are optional; stay back from exposed edges.',V,'Azenhas do Mar village viewpoint')
place('macas','Praia das Maçãs promenade',38.825,-9.4696,'An easy seaside promenade and an open horizon.','A second low-effort coastal stop, reached by a short bus or drive rather than an assumed cliff path.',V,'Praia das Maçãs beach')
city('azenhas','Azenhas do Mar',38.841,-9.462,'azenhas','White cliff village and Atlantic horizon',45,46,[110,160],[14,26],['Train to Sintra, then check the current coastal bus.','The connection and wait are part of the estimate.'],['Check the last coastal bus back to Sintra.'],V,rural=True)
route('azenhas','azenhas','The cliff-village postcard','Two coastal stops with an easy transfer',['azenhas','macas'],3,['water','views','oldworld'],'Village steps + transfer',['day','sunset'],'No continuous cliff trail is implied. Use local transport between stops and leave exposed viewpoints before dark.',V,transfers=[{'from':'azenhas','to':'macas','note':'Coastal bus or short drive; not a marked walking leg.'}])
place('roca','Cabo da Roca',38.7804,-9.4989,'A lighthouse, a headland and a very wide ocean.','A compact viewpoint visit, not a hike down to isolated beaches. Keep to the marked visitor areas.',V,'Cabo da Roca lighthouse monument')
city('roca','Cabo da Roca',38.7804,-9.4989,'roca','Huge Atlantic horizon',51,50,[120,165],[14,26],['Train to Sintra or Cascais, then a regional coastal bus.'],['Check the last bus and do not rely on a remote late-night pickup.'],V,rural=True)
route('roca','roca','At the edge of the continent','A short, dramatic headland visit',['roca'],1.5,['views','water'],'Marked headland paths',['day','sunset'],'Skip in strong wind or poor visibility. No scramble to Praia da Ursa is included.',V,extra={'trailNote':'A viewpoint stop: the map is not a full cliff-hiking route.'})
V='https://www.parquesdesintra.pt/en/parks-monuments/national-palace-and-gardens-of-queluz/'
place('queluz-palace','National Palace of Queluz',38.7502,-9.257,'A royal facade without the mountain journey.','Visit the palace exterior and choose an interior ticket only after checking current availability.',V,'Palácio Nacional de Queluz facade',True)
place('queluz-garden','Gardens of Queluz',38.7488,-9.2561,'Formal terraces, fountains and ornate garden geometry.','The gardens are part of the managed paid site, not a permanently open municipal park.',V,'Queluz palace gardens Neptune',True)
city('queluz','Queluz',38.750,-9.257,'queluz-palace','Royal gardens with less travel',20,25,[55,90],[8,16],['Connect to the Sintra railway line and walk from Queluz-Belas / Monte Abraão as the planner directs.'],['Return via the suburban railway and your connection to Loures.'],V)
route('queluz','queluz','A royal garden close to home','A smaller journey with a very different atmosphere',['queluz-palace','queluz-garden'],3,['fantasy','quiet','oldworld'],'Palace and garden paths',['day'],'Check ticket and last-entry times. Fountain operation is not guaranteed.',V)
V='https://www.visitportugal.com/en/node/132946'
place('sesimbra-fort','Fortaleza de Santiago, Sesimbra',38.4426,-9.1016,'A fortress in the middle of a bright fishing bay.','Use the public waterfront; museum or interior access is a separate check.',V,'Fortaleza Santiago Sesimbra')
place('sesimbra-bay','Sesimbra bay promenade',38.442,-9.0972,'A broad arc of sea and white waterfront buildings.','An easy out-and-back promenade. You do not need to go onto the beach to enjoy the view.',V,'Sesimbra beach bay town')
city('sesimbra','Sesimbra',38.443,-9.101,'sesimbra-bay','Fishing-bay light and a relaxed promenade',66,56,[110,155],[14,26],['Check regional bus connections from Lisbon / the south bank to Sesimbra terminal.'],['Save the final bus connection or arrange a return ride.'],V,rural=True)
route('sesimbra','sesimbra','A slow lap of a fishing bay','Stone fort, promenade and sea air',['sesimbra-fort','sesimbra-bay'],3,['water','quiet','oldworld'],'Mostly flat waterfront',['day','sunset'],'This is the town bay, not the difficult access to Ribeiro do Cavalo. Choose your own out-and-back distance.',V)
V='https://www.visitportugal.com/en/content/santuario-de-nossa-senhora-do-cabo-espichel'
place('espichel-sanctuary','Cabo Espichel sanctuary',38.4203,-9.2144,'A vast courtyard beside an exposed Atlantic headland.','A dramatic exterior visit. Remain in marked public areas and respect religious-site access.',V,'Cabo Espichel sanctuary courtyard')
place('espichel-light','Cabo Espichel lighthouse',38.4149,-9.216,'A lighthouse above a huge sweep of ocean.','The outside viewpoint is the target; entering the tower is not assumed.',V,'Cabo Espichel lighthouse')
city('espichel','Cabo Espichel',38.418,-9.215,'espichel-sanctuary','Windswept sanctuary and cinematic headland',76,67,[145,200],[18,30],['Public service to the cape can be sparse.','This route is not offered as a reliable public-only outing.'],['Confirm a return vehicle before leaving Sesimbra.'],V,public=False,rural=True)
route('espichel','espichel','A sanctuary at the end of the land','One of the most cinematic short escapes',['espichel-sanctuary','espichel-light'],2.5,['views','oldworld','water'],'Exposed headland',['day'],'No unmarked cliff paths or after-dark exploration. Skip in strong wind. Bring water; services may be limited.',V)
V='https://visitsetubal.com/'
place('setubal-jesus','Convent of Jesus, Setúbal',38.5258,-8.8954,'An intricate facade in a quieter city centre.','The exterior is part of the walk; museum entry is optional.',V,'Convento de Jesus Setúbal exterior',True)
place('setubal-filipe','Fort of São Filipe',38.517,-8.9109,'A high view over the Sado estuary and Troia.','Use the permitted public approach, with a steep final climb. Check gate access.',V,'Fort São Filipe Setúbal view')
city('setubal','Setúbal',38.524,-8.893,'setubal-filipe','Sado estuary, old city and hilltop fort',60,48,[85,130],[14,26],['Connect to Fertagus for Setúbal, then walk into town.'],['Return from Setúbal station and check your Loures connection.'],V)
route('setubal','setubal','A city opening onto the estuary','Old-town stone and a hilltop Sado panorama',['setubal-jesus','setubal-filipe'],4,['views','oldworld','water'],'City lanes + steep fort approach',['day'],'The fort approach is uphill. Check access and keep the exposed climb outside the hottest hours.',V,start={'name':'Setúbal station','lat':38.5310,'lon':-8.8843})
V='https://visitsetubal.com/noticias-destaque/arrabida-sem-carros-3/'
place('arrabida-portinho','Portinho da Arrábida',38.4758,-8.9871,'A small blue bay beneath green hills.','Stay on public waterfront accesses and maintained paths; this is not a remote cove scramble.',V,'Portinho da Arrábida bay')
place('arrabida-creiro','Creiro, Arrábida',38.478,-8.9791,'Green hills meeting clear coastal light.','Use the signed access from authorised parking. Walking and shuttle logistics change seasonally.',V,'Praia do Creiro Arrábida')
city('arrabida','Arrábida',38.478,-8.984,'arrabida-portinho','Green mountain and blue coves',67,60,[140,200],[18,30],['Train to Setúbal, then the seasonal coastal bus / shuttle.','Check which beach accesses are actually operating.'],['Confirm the final coastal service before entering the park.'],V,rural=True)
d['cities']['arrabida']['travelOptions']['parkingMin']=25
route('arrabida','arrabida','Green hills, almost unreal blue','A short bay-and-coast outing with planned access',['arrabida-portinho','arrabida-creiro'],3,['water','quiet','views'],'Coastal access paths',['day'],'Seasonal vehicle restrictions apply through 15 September 2026. Use authorised Creiro parking or municipal park-and-ride; do not assume a free drive to every bay.',V)
V='https://www.visitportugal.com/en/NR/exeres/1586D65E-3A15-4D85-B1A2-FA723B7F0A7C'
place('alcochete-water','Alcochete waterfront',38.7569,-8.9613,'A broad estuary horizon and low waterfront streets.','A gentle river-edge and village loop, not a walk into the protected marshes.',V,'Alcochete waterfront pier')
place('alcochete-church','São João Baptista, Alcochete',38.7554,-8.9624,'A stone church within quiet white lanes.','Use the church exterior as a landmark through the older streets.',V,'Igreja São João Baptista Alcochete')
city('alcochete','Alcochete',38.757,-8.962,'alcochete-water','White lanes and an enormous estuary sky',38,32,[65,105],[12,22],['Check the current regional connection from Oriente across the Vasco da Gama bridge to Alcochete.'],['Check the bus back to Oriente before a late sunset stop.'],V)
route('alcochete','alcochete','Sky, water and white lanes','The lower-key alternative to a crowded viewpoint',['alcochete-water','alcochete-church'],2.5,['quiet','water','oldworld'],'Mostly flat',['day','sunset'],'Stay on the town waterfront. Saltmarshes and nature reserve paths are not casual after-dark detours.',V)
V='https://www.bacalhoa.pt/pt/bacalhoa-buddha-eden'
place('buddha','Bacalhôa Buddha Eden',39.2705,-9.1457,'Giant Buddhas in a green sculpture landscape.','A self-directed garden visit on the estate’s signed paths. Buy/check the current ticket directly with the garden.',V,'Buddha Eden garden Buddha',True,19)
city('buddha','Buddha Eden',39.270,-9.146,'buddha','Sculptures and an unexpected garden world',68,46,[130,185],[16,30],['Regional transport can get you to Bombarral, not the garden gate.','The final 4–5 km is not included as a casual roadside walk: use a booked local ride.'],['Book or confirm the return from the garden; do not assume rides will be waiting.'],V,public=False,rural=True)
route('buddha','buddha','A different world in a garden','Sculpture, terraces and space to wander',['buddha'],3,['fantasy','quiet'],'Managed garden paths',['day'],'Paid, gated garden. Check current hours and last entry. Do not interpret the tourist phrase “free visit” as free admission.',V,extra={'trailNote':'Explore the garden’s signed paths; the map pin is the entrance, not a full internal trail.'})
V='https://www.visitportugal.com/en/NR/exeres/150D8789-B8A5-4C11-B213-8EAD2945A2B1'
place('peniche-fort','Fortress of Peniche',39.3538,-9.3810,'A coastal fortress with a serious past.','Look around the harbour and fortress exterior. The museum is a separate visit with opening and ticket rules.',V,'Fortress Peniche exterior',True)
place('carvoeiro','Cabo Carvoeiro',39.3602,-9.4072,'Layered limestone, crashing sea and the Berlengas beyond.','Use marked public viewpoints. Coastal roads between viewpoints are not a footpath just because a map joins them.',V,'Cabo Carvoeiro lighthouse cliffs')
city('peniche','Peniche',39.358,-9.381,'carvoeiro','Limestone cliffs and a working harbour',97,67,[115,170],[18,32],['Regional coach to Peniche bus terminal.','The cape may need an additional local ride; the town itself is walkable.'],['Save a confirmed regional-coach return before leaving the town.'],V,rural=True)
route('peniche','peniche','A coast carved by the ocean','Harbour history, then a dramatic headland',['peniche-fort','carvoeiro'],3.5,['views','water'],'Two short walks + transfer',['day'],'Use local transport between the fort and cape if paths are unclear. No exposed scrambling. Rides are less certain outside town.',V,transfers=[{'from':'peniche-fort','to':'carvoeiro','note':'Drive / local ride to the cape; avoid assuming a continuous coastal footpath.'}])
d['routes'][-1]['travelOptions']={'publicSuitable':False}
V='https://www.visitlisboa.com/en/regions/caparica'
place('caparica','Costa da Caparica promenade',38.6430,-9.2384,'A long Atlantic horizon with almost no hill climbing.','Choose an out-and-back length along the town promenade, staying on public paths rather than soft sand.',V,'Costa da Caparica promenade')
place('capuchos','Convento dos Capuchos viewpoint',38.6485,-9.2300,'Look over the coast from the escarpment.','A separate upper viewpoint: check gate hours and use a road transfer if the walking approach is unclear.',V,'Convento Capuchos Caparica viewpoint')
city('caparica','Costa da Caparica',38.644,-9.237,'caparica','Atlantic promenade and wide open sky',39,37,[85,125],[12,24],['Check the current bus from Lisbon / the south-bank interchange to Costa da Caparica.'],['Return from the town bus terminal, not an isolated beach access.'],V)
route('caparica','caparica','Let the horizon do the work','An easy promenade with an optional upper viewpoint',['caparica','capuchos'],3,['water','quiet','views'],'Promenade + optional transfer',['day','sunset'],'Skip the upper viewpoint and extend the flat promenade if you prefer. Access and gate hours are not guaranteed.',V,transfers=[{'from':'caparica','to':'capuchos','note':'Optional local transport uphill; skip for a flat walk.'}])
V='https://www.visitportugal.com/en/content/santarem'
place('portassol','Jardim das Portas do Sol',39.2326,-8.6752,'Ribatejo plains stretching far below the walls.','A town garden viewpoint that feels very different from the Atlantic coast. Check garden opening hours.',V,'Portas do Sol Santarém garden')
place('santarem-graca','Igreja da Graça, Santarém',39.2334,-8.6781,'A carved rose window in quiet old streets.','Wander the historic centre between the church and garden. The interior is a separate access check.',V,'Igreja da Graça Santarém')
city('santarem','Santarém',39.236,-8.681,'portassol','A hilltop town over the Ribatejo plain',66,46,[80,120],[14,26],['Use CP to Santarém.','The railway station is below town: allow a steep climb or a local bus.'],['Leave time for the descent / local bus to the station.'],V)
route('santarem','santarem','A balcony over the plain','Stone lanes and a very big inland view',['portassol','santarem-graca'],3,['views','oldworld','quiet'],'Hilltop town',['day'],'Inland heat can be much stronger than sea breezes. The station-to-town climb is not included in the short town loop.',V)
V='https://www.centerofportugal.com/'
place('foz','Foz do Arelho lagoon shore',39.4290,-9.2235,'Lagoon blue on one side, Atlantic sky on the other.','A gentle shore-and-promenade outing. Use boardwalks / public paths, without entering dunes or crossing tidal channels.',V,'Foz do Arelho lagoon')
place('foz-boardwalk','Foz do Arelho coastal boardwalks',39.4391,-9.2291,'Timber paths and a huge sweep of coast.','Follow maintained boardwalks and signed accesses. Turn around if wind or a closure makes the exposed section uninviting.',V,'Passadiços Foz do Arelho')
city('foz','Foz do Arelho',39.435,-9.226,'foz','Lagoon light, dunes and wooden viewpoints',93,63,[135,190],[18,32],['Coach to Caldas da Rainha, then a local service to Foz do Arelho.','Check the local connection; this is not a direct Lisbon train trip.'],['Protect the last local connection back to Caldas before the coach to Lisbon.'],V,rural=True)
route('foz','foz','Where the lagoon meets the ocean','A calm, wide-sky escape when inland feels too hot',['foz','foz-boardwalk'],3,['water','quiet','views'],'Promenade + boardwalk',['day','sunset'],'No swimming advice is implied. Stay on maintained paths and leave exposed boardwalks before dark.',V)
for r in d['routes']:
 r.setdefault('verdict',{});r['verdict'].setdefault('worth',r['subtitle']);r['verdict'].setdefault('skip','Skip the full outing if arrival is too close to closing time or the return is uncertain.')
 if r['city']=='sintra':r['carAccess']='Park in peripheral / town car parks. Private traffic is not permitted on the Pena approach roads; the final leg is a shuttle or signed hike.'
 if r['id']=='sintra-peaks':r['travelOptions']={'parkingMin':20}
 r['returnToCar']=abs(r['start']['lat']-r['end']['lat'])+abs(r['start']['lon']-r['end']['lon'])>.001
r=d['routes'];d['version']='5.0.0';d['built']='2026-09-06';d['fuel']={'date':'2026-09-02','source':'https://precoscombustiveis.dgeg.gov.pt/estatistica/preco-medio-diario','petrol':2.022,'diesel':2.019,'units':'EUR/litre','note':'DGEG national daily averages, not your chosen pump.'};d['plan']=['lisbon-classic','sintra-gardens','ericeira','buddha','tomar'];d['transportNote']='Planning estimates from the approximate 2660-213 base. Not live traffic, quotes or timetables.'
d['pickedFood']=[{'id':'food-prado','name':'Prado','lat':38.71008,'lon':-9.13475,'kind':'restaurant','badge':'MICHELIN Guide listed','note':'Farm-to-table. Optional, not part of the walking route. Check current menu and booking.','price':'€€','source':'https://guide.michelin.com/gr/en/lisboa-region/lisboa/restaurant/prado'},{'id':'food-bahr','name':'BAHR','lat':38.71074,'lon':-9.14343,'kind':'restaurant','badge':'MICHELIN Guide listed','note':'A rooftop setting; a pricier option. Check current menu and booking.','price':'€€€','source':'https://guide.michelin.com/en/lisboa-region/lisboa/restaurant/bahr'},{'id':'food-drogaria','name':'Drogaria','lat':38.7053,'lon':-9.1677,'kind':'restaurant','badge':'MICHELIN Guide listed','note':'Portuguese cooking near Lapa. Check current menu and hours.','price':'€€','source':'https://guide.michelin.com/pt/pt_PT/lisboa-region/lisboa/restaurant/drogaria'},{'id':'food-azenhas','name':'Azenhas do Mar restaurant','lat':38.8402,'lon':-9.4617,'kind':'restaurant','badge':'Official tourism listing','note':'Coastal view and seafood. Current prices and nutrition are not assumed.','price':'Menu varies','source':'https://www.visitportugal.com/en/NR/exeres/8819E97D-9059-424C-9FB9-49B4F04EA6CF'}]
(P/'catalog.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(P/'new-photos.json').write_text(json.dumps(photos,ensure_ascii=False,indent=2))
print(len(d['cities']),len(d['routes']),len(d['places']),len(photos))
